### ISSUE TITLE
Add >= version constraints to setup.py? 

### ISSUE THREAD

**Issue by tseemann** [mgalardini/pyseer#102]
No version constraints:

https://github.com/mgalardini/pyseer/blob/master/setup.py#L66-L76

But docs specify them?

python 3+ (3.6.6)
numpy (1.15.2)
scipy (1.1.0)
pandas (0.23.4)
scikit-learn (0.20.0)
statsmodels (0.9.0)
pysam (0.15.1)
glmnet_python (commit 946b65c)
DendroPy (4.4.0)

**Comment by tseemann** [comment]
Also missing things like `pybedtools`.

**Comment by mgalardini** [comment]
Those are the versions we used in development and testing, a better indication would be the [conda recipe](https://github.com/mgalardini/pyseer/blob/master/conda-recipe/meta.yaml#L30)

**Comment by tseemann** [comment]
Conda recipe doesn't specify versions either.

**Comment by tseemann** [comment]
Will you test on python 3.7 ? It's been out for 1.5 years now.  3.8 is imminent.

**Comment by mgalardini** [comment]
Yeah, that indicates that _realistically_ there are no restrictions on the versions used. The conda recipe might not have been updated in the pyseer repo but it should be the right one in the bioconda-recipes repo

**Comment by mgalardini** [comment]
Sure, it's just a matter of editing the `.tavis.yml` file

**Comment by tseemann** [comment]
Oh i thought you linked to the bioconda one.
