### ISSUE TITLE
Elastic net: lineages as folds for cross-validation

### ISSUE THREAD

**Issue by YannDussert** [mgalardini/pyseer#105]
Hi,

I am trying to implement the elastic net approach for a diploid species in R (because I am not very skilled at coding in Python), and I had a question about using lineages as folds during cross-validation.

From what I understand from reading the preprint and the code, there is a linear regression step between phenotype and each cluster to determine which lineage is less correlated with the phenotype. This lineage is then discarded from the design matrix and the lineage dictionary, and a fold_ids vector is computed from the design matrix. The length of this fold_ids vector corresponds to (total number of samples - samples in discarded lineage).

I am getting lost after this step: should the samples from the discarded lineage be also discarded from the variant matrix and the phenotype vector for the cross-validation step? If it is the case, I did not find where it is done in the code. If it is not the case, I cannot see how the cross-validation would work, with different numbers of observations for variants / phenotypes and fold IDs.

I hope my question is clear enough (I can post a small example if not) and apologize if it is obvious.

Thank you in advance for your answer.

Best regards,
Yann

**Comment by johnlees** [comment]
Hi Yann,

This may be a bug you've found:
The lineage being discarded is only needed when running the phenotype ~ lineage regression (to fix the rank) and should be kept for the elastic net. This block of code should probably only be run if `!options.wg`, and I have missed it in testing as the lineage discarded is a singleton and doesn't affect the results much.

I'll take a proper look in the debugger soon to confirm, and will get back to you here.

Cheers,
John

**Comment by johnlees** [comment]
Though it is a bit confusing that `fold_ids = np.where(lineage_clusters == 1)[1]` doesn't throw a length error if this is the case.

Anyway, Iwill check on a test dataset as soon as I can

**Comment by YannDussert** [comment]
Hi,

After looking at the code again, I might have missed something. The code for the phenotype ~ lineage regression and discarding of the less uncorrelated one is in a ```if options.lineage:``` block, so I guess it only applies to the bugwas model?

Best,
Yann

**Comment by johnlees** [comment]
Ah, that's it! The logic in those blocks is not the easiest to follow, and I had forgotten that `--lineage` and `--lineage-clusters` were different options.

Let me know if you have any more questions while re-implementing. I think the numpy code that gets the matrices in order for cross-validation etc should be pretty similar to the R equivalent
