### ISSUE TITLE
No observations found when running the fixed effects model for COG associations

### ISSUE THREAD

**Issue by anna7287** [mgalardini/pyseer#106]
Hello, 

I'm using Pyseer to look for COG associations with the fixed effects model using the below command:

pyseer --phenotypes klebcresistances.pheno --pres gene_presence_absence.Rtab --distances mash.tsv --save-m mash_mds --max-dimensions 2 > klebC_COGSs.txt.

Result:
No observations found in all genes.

Output:
24584 loaded variants
24584 filtered variants
0 tested variants
0 printed variants

I am not sure if this is normal since all of the loaded variants have been filtered out? I've tried playing around with the filters but it doesn't change the result. Do you know why all of the loaded variants are being filtered out? 

Thanks,

Anna

**Comment by mgalardini** [comment]
Hi,

you can try running it again with the `--print-filtered` option on, so that it will show the reason for filtering all of the COGs.

Best,
M

**Comment by johnlees** [comment]
This could be due to a label mismatch between the phenotype, variant and
distances files. Do the sample labels match up between the three input
files?

**Comment by anna7287** [comment]
Thanks for getting back to me so quick Marco and John!
After checking the gene_absence_presence.Rtab file I noticed the labels still had some assembly information in them, which isn't present in the distance and phenotype file. I now have a better output:

Read 158 phenotypes
Detected binary phenotype
Structure matrix has dimension (158, 158)
Analysing 158 samples found in both phenotype and structure matrix
24584 loaded variants
11925 filtered variants
12659 tested variants
12659 printed variants

Thanks a lot for your help!

Anna
