### ISSUE TITLE
k-mer association fails with IndexError #2

### ISSUE THREAD

**Issue by nenadmacesic** [mgalardini/pyseer#107]
Hi,

I am trying to run a kmer association study with PySeer 1.1.2 (installed with Conda). The kmers were generated using DSK then the combineKmers script from Seer. The distance matrix was generated using the phylogeny_distance.py script. The command I ran was:

pyseer --lmm --phenotypes dsk_files_dataset_19_phenotype.txt --kmers dsk_files_dataset_19_gwas_seer.gz --similarity st258_phylo_20190827_distances.tsv --output-patterns kmer_patterns.txt --cpu 16 > pyseer_dataset_19_gwas.txt

The output I got was:
Read 235 phenotypes
Detected binary phenotype
Setting up LMM
Similarity matrix has dimension (620, 620)
Analysing 235 samples found in both phenotype and similarity matrix
h^2 = 0.55
Traceback (most recent call last):
  File "/home/nmacesic/.conda/envs/AMR_ML2/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/nmacesic/.conda/envs/AMR_ML2/lib/python3.6/site-packages/pyseer/__main__.py", line 505, in main
    options.cpu))
  File "/home/nmacesic/.conda/envs/AMR_ML2/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/nmacesic/.conda/envs/AMR_ML2/lib/python3.6/multiprocessing/pool.py", line 376, in _map_async
    iterable = list(iterable)
  File "/home/nmacesic/.conda/envs/AMR_ML2/lib/python3.6/site-packages/pyseer/input.py", line 500, in iter_variants_lmm
    for variants, variant_mat, eof in variant_iter:
  File "/home/nmacesic/.conda/envs/AMR_ML2/lib/python3.6/site-packages/pyseer/input.py", line 558, in load_var_block
    sample_order)
  File "/home/nmacesic/.conda/envs/AMR_ML2/lib/python3.6/site-packages/pyseer/input.py", line 294, in read_variant
    '|')[1].lstrip().split())
IndexError: list index out of range

I know that there was a similar issue previously but I have checked the kmer file and there do not appear to be any issues.

Any help/advice would be much appreciated!

**Comment by johnlees** [comment]
The `combineKmers` format is not compatible with pyseer. This was previously noted, but I haven't got around to fixing it yet (https://github.com/johnlees/seer/issues/73 and https://github.com/mgalardini/pyseer/issues/74#issuecomment-495223425).

A workaround would be to run the following commands on your input file:
```
gzip -d -c dsk_files_dataset_19_gwas_seer.gz > tmp.txt
paste <(awk '{print $1, "|"}' tmp.txt) <(cut -d " " -f 2- tmp.txt) | gzip -c > dsk_files_dataset_19_gwas_seer.fixed.gz
rm tmp.txt
```
If the fixed file looks ok you can then run `mv dsk_files_dataset_19_gwas_seer.fixed.gz dsk_files_dataset_19_gwas_seer.gz` and re-run pyseer

Sorry for the inconvenience!

**Comment by johnlees** [comment]
I have now fixed this in the seer code (https://github.com/johnlees/seer/commit/4c3cbe9299de5e623f14a9451d909cb006f87f5c) but it will take a little while before this update can be pushed to bioconda

**Comment by nenadmacesic** [comment]
Thanks John - that makes sense! First time using PySeer so still figuring it all out.
