### ISSUE TITLE
k-mer annotation does not iterate

### ISSUE THREAD

**Issue by RJBeng** [mgalardini/pyseer#108]
Hello,

I am trying to annotate my k-mers with `annotate_hits_pyseer case_significant_kmers.txt references.txt case_significant_annotated_kmers.txt`

However, it only performs annotation with the first line of reference and does not iterate to the next draft reference. My reference file is tab delimited, with the first column containing the fna file name, second column containing the gff file name and the third column with either 'ref' or 'draft'. I am operating this in a conda environment and all the fna and gff files are put in the directory where the command is executed.

I cannot figure out why it does not iterate through and would appreciate if someone could help. I have also uploaded my reference.txt file 

Many thanks
Rebecca 

[references.txt](https://github.com/mgalardini/pyseer/files/4046489/references.txt)

**Comment by mgalardini** [comment]
Hi, what version of pyseer do you have installed? Try `pyseer --version`. I remember some problems with `annotate_hits_pyseer`, but those might have been fixed already. Your file looks good to me.

**Comment by RJBeng** [comment]
Hi @mgalardini I am using version 1.3.3

**Comment by mgalardini** [comment]
I see, that version should work. Would you mind sending me (mgala AT bu DOT edu) your `case_significant_kmers.txt` file and the first two genomes from `references.txt`? Specifically the following files:

```
GCF_000006925.2_ASM692v2_genomic.fna
GCF_000006925.2_ASM692v2_genomic.gff
FD01543303.fna
FD01543303.gff
```
I can then try to replicate the problem you are seeing. Thanks

**Comment by RJBeng** [comment]
[case_significant_kmers.txt](https://github.com/mgalardini/pyseer/files/4058528/case_significant_kmers.txt)

[GCF_000006925.2_ASM692v2_genomic.fna.gz](https://github.com/mgalardini/pyseer/files/4058541/GCF_000006925.2_ASM692v2_genomic.fna.gz)
[GCF_000006925.2_ASM692v2_genomic.gff.gz](https://github.com/mgalardini/pyseer/files/4058542/GCF_000006925.2_ASM692v2_genomic.gff.gz)
[FD01543303.fna.gz](https://github.com/mgalardini/pyseer/files/4058543/FD01543303.fna.gz)
[FD01543303.gff.gz](https://github.com/mgalardini/pyseer/files/4058544/FD01543303.gff.gz)

**Comment by mgalardini** [comment]
It seems to be working for me:

```
$ annotate_hits_pyseer case_significant_kmers.txt references.txt case_significant_annotated_kmers.txt
8 kmers remain
Reference 1
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -v 1 -k 8 GCF_000006925.2_ASM692v2_genomic.fna /home/mgala/Downloads/remaining_kmers.fa
[main] Real time: 0.004 sec; CPU: 0.005 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa fastmap -l 9 GCF_000006925.2_ASM692v2_genomic.fna /home/mgala/Downloads/remaining_kmers.fa
[main] Real time: 0.006 sec; CPU: 0.007 sec
0 kmers remain unannotated
```

I added an additional kmer to trigger the search in the draft genome, and that also worked:

```
$ annotate_hits_pyseer case_significant_kmers.txt references.txt case_significant_annotated_kmers.txt
9 kmers remain
Reference 1
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -v 1 -k 8 GCF_000006925.2_ASM692v2_genomic.fna /home/mgala/Downloads/remaining_kmers.fa
[main] Real time: 0.091 sec; CPU: 0.015 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa fastmap -l 9 GCF_000006925.2_ASM692v2_genomic.fna /home/mgala/Downloads/remaining_kmers.fa
[main] Real time: 0.004 sec; CPU: 0.004 sec
1 kmers remain
Draft reference 2
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa fastmap -l 9 FD01543303.fna /home/mgala/Downloads/remaining_kmers.fa
[main] Real time: 0.218 sec; CPU: 0.009 sec
1 kmers remain unannotated
```

I have used pyseer 1.3.3 for this test. Could you share your stdout/stderr output?

**Comment by mgalardini** [comment]
Closing this issue for now, can be reopened if more information is given

**Comment by RJBeng** [comment]
Hi @mgalardini, thanks for looking into this. I am getting the same output as you so I guess the problem is not because pyseer is not iterating but due to kmers not mapping to any of the draft genomes?

**Comment by mgalardini** [comment]
Oh I think I know understand your question, sorry! You were expecting the kmers to be annotated for all the genomes in the `references.txt` file, right? However, `annotate_hits_pyseer` will discard a kmer once it has been mapped, and move to the next genome in the list only if at least one kmer remains to be mapped. If you want to annotate all kmers to all genomes you should run `annotate_hits_pyseer` once for each genome, using a different `references.txt` file each time. Does that make sense to you?

**Comment by RJBeng** [comment]
Oh I see!!! Yes that answers my question! Thank you so much for your help :D

**Comment by mgalardini** [comment]
Great, sorry for taking some time to understand your question
