### ISSUE TITLE
Output the same with or without covariates

### ISSUE THREAD

**Issue by tatumdmortimer** [mgalardini/pyseer#110]
Kevin (@kevincma) and I have run into a problem using covariates with LMM in pyseer. When covariate and phenotype files have more samples than the similarity matrix, pyseer silently ignores the covariate input, and the results are the same whether or not you use the --covariates/--use-covariates flags. We do not have this issue if the similarity matrix has more samples than the phenotype/covariate matrices.

We think the following lines (88-92) in lmm.py are where the covariate matrix is being removed/ignored:

```
if cov.shape[0] == p.shape[0]:
    cov = cov.loc[intersecting_samples]
    covar = np.c_[cov.values, np.ones((p.shape[0], 1))]
else:
    covar = np.ones((p.shape[0], 1))
```
It appears that the covariate matrix is being subsampled to the original size of the phenotype matrix before the phenotype matrix is subsampled to the samples in the similarity matrix, so cov.shape[0] > p.shape[0] and the else block is invoked. 

We were able to fix this issue by subsampling the input phenotype and covariate files to the exact samples in the similarity matrix. However, we think it would be an improvement to pyseer if the covariate matrix was also downsampled to the samples present in both matrices (instead of just samples with a phenotype) or if a warning was printed to let the user know that the covariate matrix was the wrong size and was not being included.

**Comment by mgalardini** [comment]
Hi @tatumdmortimer, thanks for reporting this issue! I absolutely agree with you, I will fix this as soon as possible, no reason why it should not work as with the similarity matrix.

**Comment by mgalardini** [comment]
After reviewing the issue, I think the best cause of action is to stop pyseer and give an error message when covariates and phenotype file don't have the same samples. This is due to the feature of saving/loading the LMM cache, which makes checking the samples in the similarity matrix not possible in all cases. Could you give the proposed change a try? (you can try running the code from [this branch](https://github.com/mgalardini/pyseer/tree/issue_110))

**Comment by johnlees** [comment]
Another option would be to remove the lmm cache feature (as in my experience this isn't particularly useful, it doesn't save that much time as we generally give K as input, which is the main time save of using this in fast-lmm) and then take the intersection of samples between p and cov, as we do for p and K. Then this would work irrespective of input, and show a useful message with the number of samples actually used

**Comment by tatumdmortimer** [comment]
I compared the following:

1) no covariate
2) covariate input with the same samples as phenotype input, but more samples than similarity matrix
3) covariate, phenotype, and similarity all have the same samples

Using the new branch, #2 and #3 have the same output, while in previous tests the output from #2 was the same as #1. I never got the error message you added in the new branch, but my input phenotype and covariate files have always had the same samples. I can remove samples from one or the other and test again if that would be helpful.

**Comment by mgalardini** [comment]
That is fine, thanks for having a go at it! I have added some tests and the error message does pop up if you have less samples than the phenotype file and/or a mismatch. @johnlees I will think about it and maybe implement it in the next few days; we might be breaking someone's (?) pipeline by removing a feature.

**Comment by kevincma** [comment]
Thanks all for the quick responses!

**Comment by johnlees** [comment]
@mgalardini seeing as you have a working fix so quickly, and as you point out it's probably best not to carve options away, I think we may as well stick with it!

**Comment by mgalardini** [comment]
Thanks again for reporting this issue! @johnlees I see the tests are failing for some funny business going on with glmnet_py. I might open an issue when I can see what the problem is

**Comment by johnlees** [comment]
@mgalardini there's a load of rubbish in there from glmnet_py using functions which will be removed in scipy 2.0.0 (which we should probably deal with/make a pull request at some point), but it looked like the fail was possibly due to this change:
```
=================================== FAILURES ===================================
____________________ TestInitialiseLmm.test_initialise_lmm _____________________
AttributeError: 'str' object has no attribute 'conjugate'
The above exception was the direct cause of the following exception:
self = <tests.lmm_test.TestInitialiseLmm testMethod=test_initialise_lmm>
    def test_initialise_lmm(self):
        p = pd.read_csv(P_BINARY,
                        index_col=0,
                        sep='\t')['binary']
        cov = pd.DataFrame([])
        x, y, z = initialise_lmm(p, cov, S,
                                 lmm_cache_in=None,
                                 lmm_cache_out=None)
        self.assertEqual(x.shape[0], 50)
        self.assertAlmostEqual(y.findH2()['nLL'][0],
                               35.7033778)
        self.assertAlmostEqual(z, 0.0)
        # covariates
        cov = pd.read_csv(COV, index_col=0,
                          header=None,
                          sep='\t')
        x, y, z = initialise_lmm(p, cov, S,
                                 lmm_cache_in=None,
>                                lmm_cache_out=None)
tests/lmm_test.py:85: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyseer/lmm.py:115: in initialise_lmm
    result = lmm.findH2()
pyseer/fastlmm/lmm_cov.py:476: in findH2
    min = minimize1D(f=f, nGrid=nGridH2, minval=minH2, maxval=maxH2)
pyseer/fastlmm/mingrid.py:40: in minimize1D
    [evalgrid,resultgrid] = evalgrid1D(f, evalgrid = evalgrid, nGrid=nGrid, minval=minval, maxval = maxval  )
pyseer/fastlmm/mingrid.py:99: in evalgrid1D
    fevalgrid = f(evalgrid[i])
pyseer/fastlmm/lmm_cov.py:471: in f
    res = self.nLLeval(h2=x,**kwargs)
pyseer/fastlmm/lmm_cov.py:653: in nLLeval
    S,U = self.getSU()
pyseer/fastlmm/lmm_cov.py:155: in getSU
    self.setSU_fromK()
pyseer/fastlmm/lmm_cov.py:95: in setSU_fromK
    K_ = self.linreg.regress(Y=self.K)
pyseer/fastlmm/lmm_cov.py:875: in regress
    self.set_beta(Y=Y)
pyseer/fastlmm/lmm_cov.py:869: in set_beta
    self.Xdagger = la.pinv(self.X)       #SVD-based, and seems fast
<__array_function__ internals>:6: in pinv
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
a = array([['1', '1', 1.0],
       ['2', '2', 1.0],
       ['3', '0', 1.0],
       ['4', '1', 1.0],
       ['5', '2', 1.0]....0],
       ['47', '2', 1.0],
       ['48', '0', 1.0],
       ['49', '1', 1.0],
       ['50', '2', 1.0]], dtype=object)
rcond = array(1.e-15), hermitian = False
    @array_function_dispatch(_pinv_dispatcher)
    def pinv(a, rcond=1e-15, hermitian=False):

E       TypeError: loop of ufunc does not support argument 0 of type str which has no callable conjugate method
../../../miniconda/envs/test-environment/lib/python3.6/site-packages/numpy/linalg/linalg.py:1960: TypeError
```

**Comment by mgalardini** [comment]
@johnlees you're right! I will take a look when I get the chance to fix glmnet_py as well
