### ISSUE TITLE
No observations of variant in selected samples

### ISSUE THREAD

**Issue by jsan4christ** [mgalardini/pyseer#112]
$ pyseer --phenotypes ../../pheno_drug_lop.tsv --vcf ../analysis_ready_bams/PRES_all.vcf --load-m mash/mash_mds.pkl --min-af 0.02 --max-af 0.98 >  lopU_SNPs1.txt

---
No observations of NC_001802.1_9169_C in selected samples
No observations of NC_001802.1_9170_C in selected samples
No observations of NC_001802.1_9171_T in selected samples
No observations of NC_001802.1_9172_T in selected samples
No observations of NC_001802.1_9173_G in selected samples
No observations of NC_001802.1_9174_A in selected samples
No observations of NC_001802.1_9175_G in selected samples
No observations of NC_001802.1_9176_T in selected samples
No observations of NC_001802.1_9177_G in selected samples
No observations of NC_001802.1_9178_C in selected samples
No observations of NC_001802.1_9179_T in selected samples
No observations of NC_001802.1_9180_T in selected samples
No observations of NC_001802.1_9181_C in selected samples
9181 loaded variants
9181 filtered variants
0 tested variants
0 printed variants

Any idea why I get this error?? I generated the combined vcf using both Haplotypecaller and unifiedgenotyper and both sets give me the same results. 

Thanks,

**Comment by mgalardini** [comment]
Hi,

I believe you might have called your samples differently between your input vcf and the other inputs of pyseer. Could you check that and try again?

M

**Comment by jsan4christ** [comment]
Apart from the .g.vcf extension, nothing is different. I have tried sed -i 's/.g.vcf//g' ../analysis_ready_bams/vcf/PRES2.all.vcf to get rid of the extensions but that too did not help. 

If helps, I can share the files

**Comment by mgalardini** [comment]
Would you mind sharing a few of the sample names that are present in each
of the input files?

**Comment by jsan4christ** [comment]
PRES308 0
RES047  1
RES106  1
RES156  1
RES169  1
RES173  1
RES175  1
RES313  1
RES351  1
RES402  1
RES415  1
RES432  1
RES443  1
RES452  0
RES454  0
RES551  1
RES554  1
RES560  0
RES624  1
RES647

**Comment by jsan4christ** [comment]
Yes, here below;
PRES308, RES047, RES106, RES156, RES169, RES173, RES175 ,RES313, RES351

**Comment by mgalardini** [comment]
Hi, I see that you vcf file has only one sample, called "20". Your VCF file should have the same samples as the other input file

**Comment by jsan4christ** [comment]
Thanks for catching that, for anyone having a similar problem, it is because, the SM option of your bam file is not set. To solve it; I used:

parallel --compress  --tmpdir /analyses/tmp  'java -Dpicard.useLegacyParser=false -Xmx100g -Djava.io.tmpdir=/analyses/tmp -jar /usr/local/biotools/picard.jar AddOrReplaceReadGroups -I sorted/{}.bam -O addReadGroups/{}.bam -RGID 4 -RGLB lib1 -RGPL illumina -RGPU unit1 -**RGSM {}**' ::: $(ls sorted/*.bam | xargs -n 1 basename | cut -d "." -f1 | uniq)

This will assign the sample name and then you won't have trouble with your joint variant calling.
