### ISSUE TITLE
Burden testing questions

### ISSUE THREAD

**Issue by apredeus** [mgalardini/pyseer#117]
Hello Marco, John, 

I'm running burden testing on the same dataset I've been asking questions about (~3k Salmonella isolates). So far it's been really good, and I've generated some very good candidates. However, many things are not clear to me, and since the subject is not covered in the tutorial much, I figured maybe I can bother you here a bit? Please let me know if you'd prefer email, etc. 

- Is it possible to use LMM with burden testing and does it make sense at all? I've been using fixed effects and mash distances, but it doesn't (seem to) work that well, since my isolates are often very close to each other. Perhaps it's a good idea to use mash with higher sketch size? 

- Is it possible to use higher frequency LoFs together with lower frequency ones? I've tried selecting variants with MAF < 5%, or even all the LoFs in the dataset, but all variants end up being filtered. Why is this happening? (by the way, using --print-filtered does exactly nothing in this case - nothing is printed). Pseudogene accumulation is a known thing in Salmonella adaptation, and LoFs are not necessarily rare (but still would probably decay and accumulate mutations). I would like to include these, if that's possible. 

- Is it possible to print stats for each "burden" feature, e.g. how many variants have been added per gene/pathway? Would be good for debugging and keeping track of individual variants, I think. 

- How should one determine significance for burden test? LRT p-value of less than 0.05/<n.genes>? 

Thank you in advance and for answering other questions as well - you've been very helpful, and I really appreciate it.

**Comment by johnlees** [comment]
- If you are finding that some of the mash distances are zero increasing the sketch size can help (10^4 or maybe 10^5 usually works for most species). But generally I'd recommend using the LMM instead, as you suggest. It works with burden testing too.
- I would suggest doing your AF filtering with e.g. bcftools for these more complex cases. Essentially, try and create a single vcf for everything you want to include, and then set the pyseer AF filtering to zero. In burden testing mode it should be the AF of the region that is filtered on (so if it includes a number of common variants the AF can be pushed up and filtered out that way).
- We don't currently have that feature, but it is a good suggestion. A workaround would be to use `bcftools view` with your regions as input, which can give a count for each one. If you aren't filtering in pyseer it should be the same.
- I think that is a sensible choice, and what I have used in the past

**Comment by apredeus** [comment]
Thank you very much for all the answers. As always, much appreciated. 

One last thing: the filtering does not seem to work. Perhaps is the issue with how I created/annotated the VCF files (Snippy, annotation with snpEff, then merge with bcftools)? I'm having similar troubles with trying to run regular LMM on a VCF of full set of all variants (not burden testing - just GWAS). 

When I'm running 

`pyseer --min-af 0.0001 --max-af 1 --vcf all_lof_P125.vcf.gz --phenotypes nf_eb_ent_3083.pheno --burden features_P125.tsv --distances mash.tsv --print-filtered`

I get the empty output still, with the following logs:

> No observations of P125109_00001 in selected samples
> ...................
> No observations of P125109_05023 in selected samples
> 4606 loaded variants
> 4606 filtered variants
> 0 tested variants
> 0 printed variants

I'll try to debug it myself if the problem is VCF - if you could just confirm that I'm turning off AF filtering right (setting --min-af to 0 throws an error).

**Comment by johnlees** [comment]
Yes, the AF filtering is being turned off correctly. Usually this error is due to sample labels in the VCF file not matching up with the pheno file
