### ISSUE TITLE
Error parsing line with summarise_annotations.py

### ISSUE THREAD

**Issue by nickp60** [mgalardini/pyseer#119]
I am running into an issue running summarise_annotations.py on a set of annotated kmers;  I tracked down the issue to the part of the file attached. The kmers were annotated with 3 reference genomes (E. coli ATCC8739, Sakai, and MG1655, downloaded from NCBI). Can you advise how to avoid this?

```
$ python summarise_annotations.py tmp.txt >summ.txt
Traceback (most recent call last):
  File "/home/nickp60/GitHub/pyseer/scripts/summarise_annotations.py", line 56, in <module>
    (position, down, inside, up) = annotation.split(";")
ValueError: not enough values to unpack (expected 4, got 1)
```

I am running the current master branch commit `77b4fa5ce`.  Thanks in advance!

[summarize-error-input.txt](https://github.com/mgalardini/pyseer/files/4614557/summarize-error-input.txt)

**Comment by mgalardini** [comment]
I see that one k-mer (`CGACAAAAT`) doesn't have any annotated hit, and that breaks the script. I'll add something to catch situations like this and warn the user with a message.

**Comment by mgalardini** [comment]
I believe this has now been fixed. Could you download [the latest version of the script](https://raw.githubusercontent.com/mgalardini/pyseer/master/scripts/summarise_annotations.py) and check yourself? Thanks

**Comment by nickp60** [comment]
Fantastic, thanks so much @mgalardini !!!
