### ISSUE TITLE
--max-missing in pyseer is not working.

### ISSUE THREAD

**Issue by neginmb** [mgalardini/pyseer#120]

**Comment by johnlees** [comment]
Can you please provide more details? The version you are using, the command being run, the file that produces this behaviour, what is expected, and what is seen?

If possible, a small file (for example a single variant with missing data) that reproduces your problem would help us.

**Comment by neginmb** [comment]
I am using pyseer v1.3.0, this is my command and this is an example vcf file:
pyseer --phenotypes pheno-continuous.tsv --vcf normalized_test.vcf \
--no-distances \
--max-missing 0.01 \
> test-output.txt

My file had high missingness, but it didn't get filtered by this command.
How can I send my example file to you?

**Comment by mgalardini** [comment]
Hi, see [here](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) for a guide on how to attach files to a github issue

**Comment by neginmb** [comment]
Hi, this is my file:
[normalized_test.zip](https://github.com/mgalardini/pyseer/files/4622120/normalized_test.zip)

**Comment by mgalardini** [comment]
Hi, I think the issue has now been fixed. Could you try to download the latest master and try it yourself? Thanks

**Comment by neginmb** [comment]
I couldn't run the latest Master. What if I upgrade my pyseer directly with pip command? then the upgraded one has the bug fixed?

**Comment by mgalardini** [comment]
You can download the latest master [here](https://github.com/mgalardini/pyseer/archive/master.zip); unzip it, `cd` into it and then run your original command like this: `python3 pyseer-runner.py [ARGS]`.
