### ISSUE TITLE
Can't install with conda on Windows due to "incompatibility" with 0 other packages

### ISSUE THREAD

**Issue by dkassler** [mgalardini/pyseer#121]
When following the [installation instructions](https://pyseer.readthedocs.io/en/master/installation.html) in my Anaconda3 prompt, I run across the following error:

```
>conda install pyseer
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

The message ends there, though - there are no actual incompatible packages listed. Is this a known problem with `pyseer`?

I'm running Windows 10, with the following versions of anaconda and python:
```
>conda list anaconda
# packages in environment at C:\Users\Daniel\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0
anaconda                  custom                   py37_1
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.12                   py37_0
anaconda-project          0.8.3                      py_0    conda-forge
>python --version
Python 3.7.6
```

**Comment by johnlees** [comment]
Although pyseer is a noarch package (so is available for Windows), it may well be the case that not all of the dependencies include a Windows version. 
bioconda doesn't support Windows (and so unfortunately, neither do we through this installation method), so this won't be tested before upload, meaning it's possible to get these errors even though it looks like the package is available. I'm not sure why your message was truncated, but that might show the unsupported packages.

I would recommend either running a virtual machine with ubuntu in your windows environment, or using the docker image for the package available on quay.io

Sorry that we cannot offer direct support in this case
