### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by vealvarez** [mgalardini/pyseer#123]
Hi! I am using Biolinux (Ubuntu 14.04 LTS) and when I run this command:

pyseer --vcf snps.vcf.gz --phenotypes resistances.pheno --wg enet --save-vars output/ma_snps --save-model penicillin.lasso --cpu 4 --alpha 1 > selected.txt

I get this error:
usage: pyseer [-h] --phenotypes PHENOTYPES
              [--phenotype-column PHENOTYPE_COLUMN]
              (--kmers KMERS | --vcf VCF | --pres PRES) [--burden BURDEN]
              [--distances DISTANCES | --load-m LOAD_M]
              [--similarity SIMILARITY | --load-lmm LOAD_LMM]
              [--save-m SAVE_M] [--save-lmm SAVE_LMM]
              [--mds {classic,metric,non-metric}]
              [--max-dimensions MAX_DIMENSIONS] [--no-distances]
              [--continuous] [--lmm] [--lineage]
              [--lineage-clusters LINEAGE_CLUSTERS]
              [--lineage-file LINEAGE_FILE] [--min-af MIN_AF]
              [--max-af MAX_AF] [--filter-pvalue FILTER_PVALUE]
              [--lrt-pvalue LRT_PVALUE] [--covariates COVARIATES]
              [--use-covariates [USE_COVARIATES [USE_COVARIATES ...]]]
              [--print-samples] [--print-filtered]
              [--output-patterns OUTPUT_PATTERNS] [--uncompressed] [--cpu CPU]
              [--block_size BLOCK_SIZE] [--version]

I installed pyseer using conda and the version that installed is 1.1.0. I I can't manage to install version 1.3.6 to see if it fixs the problem.

Please, could you help me?

Thanks in advance.

**Comment by johnlees** [comment]
You will have to install a newer version to get access to these features. You need at least v1.2, but would recommend getting the latest version. So I would recommend running:
```
conda create -n pyseer pyseer>=1.3.6
```
To create a new conda environment with pyseer at a sufficient version. Let me know if you have any problems with that

**Comment by mgalardini** [comment]
Closing for lack of updates
