### ISSUE TITLE
bad-chisq

### ISSUE THREAD

**Issue by zmy24** [mgalardini/pyseer#125]
Hi,
I have some question about the output of pyseer.
![微信截图_20201015100903](https://user-images.githubusercontent.com/72899591/96068372-7d1c7180-0ece-11eb-8bd8-9b3df2a7bed8.png)
736652's af is smaller than 861690, Why the variant 861690 has the note of 'bad-chisq' instead of 736652?

**Comment by johnlees** [comment]
This is not just a function of allele frequency, the case/control bias also plays a part. The note is added if any of the table entries are 0 or 1, or if more than one entry is less than 5, where the table entries are 2x2 case vs control and variant vs no variant

**Comment by mgalardini** [comment]
Closing for lack of updates
