### ISSUE TITLE
Significant hits when measured heritability is zero 

### ISSUE THREAD

**Issue by Morteza-M-Saber** [mgalardini/pyseer#138]
Running pyseer LMM on a set of unitigs derived from cholera samples, at some concentrations of antibiotics while heritability is measures as zero (h^2 = 0.00), there are significant hits in the results.  I was wondering what can be the explanation of the results! can they be considered as real hits or they should be ignored as false positives? 
Thanks.

**Comment by johnlees** [comment]
I wouldn't take the listed heritability estimate as gospel, especially with a binary phenotype. I've seen it shunted to either end (0 or 1) when the true value should be somewhere in-between. You might want to have a look with another method which better models h^2 if you are interested in its value – the pyseer estimation is pretty 'rough and ready'
