### ISSUE TITLE
AssertionError in dendropy when running scripts/phylogeny_distance.py

### ISSUE THREAD

**Issue by julibeg** [mgalardini/pyseer#141]
One of my trees throws `assert break_on_node is not None or target_edge is not None` on the second call to `tree.reroot_at_midpoint(update_bipartitions=True, suppress_unifurcations=False)` in `scripts/phylogeny_distance.py`. Apart from that, the tree file seems to be OK.

https://github.com/mgalardini/pyseer/blob/5c821d3616348ce2f6b9eff80c43ecdf470ceec7/scripts/phylogeny_distance.py#L54

I don't have much experience with dendropy and don't fully understand why two calls are necessary (and if such usage is intended by the dendropy devs). Therefore, I have opened this issue here. If you think that the cause is an internal bug in dendropy, I will open an issue there.

To reproduce the error run:
```
import dendropy

tree = dendropy.Tree.get(path='error.tree', schema='newick',
                         preserve_underscores=True)
tree.reroot_at_midpoint(update_bipartitions=True, suppress_unifurcations=False)
tree.reroot_at_midpoint(update_bipartitions=True, suppress_unifurcations=False)
```
after unzipping [error.tree.gz](https://github.com/mgalardini/pyseer/files/5992582/error.tree.gz).

**Comment by johnlees** [comment]
Thanks for raising this. This was included due to an error in older versions of dendropy, which has now been fixed upstream. I can get rid of the second midpoint root and pin the dendropy version
