### ISSUE TITLE
Filtering based on maximum allele frequency

### ISSUE THREAD

**Issue by neginmb** [mgalardini/pyseer#146]
Hi,
How can I remove filtering based on maximum allele frequency. I tried with: --max-af 1.0
But, it didn't work!
Thanks in advance

**Comment by mgalardini** [comment]
Hi, I believe that should work; maybe you could also try `--min-af 0 --max-af 1`?

**Comment by neginmb** [comment]
I see that even after setting --min-af 0 --max-af 1, still around 20% of variants are filtered. I was wondering if there are more filters that I need to turn off to have all the variants!?

**Comment by mgalardini** [comment]
One possibility is that for some variants you have many missing samples:

```
--max-missing MAX_MISSING
                        Maximum missing (vcf/Rtab) [Default: 0.05]
```

Maybe try setting `--max-missing 1`?

**Comment by neginmb** [comment]
No, even after adding --max-missing 1, still 20% of my variants are getting filtered!

**Comment by mgalardini** [comment]
Could you please share your command line arguments?

**Comment by neginmb** [comment]
pyseer --phenotypes phenotype.tsv --vcf variant_file.vcf \
--distances distance_file.tsv --max-dimensions 4 --lineage --lineage-file lineage_file.txt \
--min-af 0 \
--max-af 1 \
--max-missing 1 \
--output-patterns output_pattern_file.txt --print-samples \
> output_file.txt

**Comment by mgalardini** [comment]
Can you add the `--print-filtered` option to see which variants were filtered and why?

**Comment by mgalardini** [comment]
It could also help if you posted the output that is given in the terminal, if you don't mind?

**Comment by neginmb** [comment]
Adding the --print-filtered option did not work for me.  But, my output looks like this:
Read ... phenotypes
Detected continuous phenotype
Structure matrix has dimension (..., ...)
Analyzing... samples found in both phenotype and structure matrix
Writing lineage effects to ...txt
... loaded variants
... filtered variants
... tested variants

**Comment by mgalardini** [comment]
Hi, there should be a `notes` column in the output, which should indicate why a particular variant was filtered (https://pyseer.readthedocs.io/en/master/usage.html#output). Would you mind looking into that?

**Comment by johnlees** [comment]
It may also help if you could share an example of one of the variants that is being filtered out?

**Comment by neginmb** [comment]
I could see nothing in the note column because my output does not include
the filtered variants. So, now, my question is how I can also include the
filtered variants?

**Comment by mgalardini** [comment]
Just to be totally clear you don't see those variants when using the `--print-filtered` argument? Can you share a minimal input for me to reproduce your problem please?

**Comment by neginmb** [comment]
How can I share a file with you privately?

**Comment by mgalardini** [comment]
google me to find an email address you can use (Marco Galardini)

**Comment by mgalardini** [comment]
Thanks, I think I got it: what we mean by `filtering` in the output is actually `pre-filtering`, which never gets printed, even with the `--print-filtered` argument on. I think we could change that so that it generates less confusion.

Regarding your actual data, those variants are prefiltered because there are too few samples with the variant, and so the initial t-test fails. So that is the correct behaviour, it's just that we were not printing those variants.

**Comment by neginmb** [comment]
Thanks for looking into that. 
Regarding your answer, what is the minimum frequency of variants needed to conduct a t-test in pyseer?

**Comment by mgalardini** [comment]
I think in your case the problem is also the low sample size: the original SEER paper has some indication on which sample size is appropriate to have sufficient statistical power: https://www.nature.com/articles/ncomms12797
