### ISSUE TITLE
Format of lineage.txt

### ISSUE THREAD

**Issue by buihoangphuc412** [mgalardini/pyseer#149]
I account the population structure into elastic model.
`pyseer --vcf snps.vcf.gz --phenotypes amox.txt --wg enet --load-vars output/ma_snps --lineage-clusters lineage_clusters.txt --sequence-reweighting`
Read 129 phenotypes
Detected binary phenotype
All samples with a phenotype must be present in the lineage file
I wondered the format of the lineage file is wrong. Could you help to fix it?

[amox.txt](https://github.com/mgalardini/pyseer/files/6434057/amox.txt)

[lineage_clusters.txt](https://github.com/mgalardini/pyseer/files/6434050/lineage_clusters.txt)

**Comment by mgalardini** [comment]
Hi, the lineage file should be tab delimited and contain no header; yours is comma-separated and does contain an header

**Comment by buihoangphuc412** [comment]
Thank you. I fixed
