### ISSUE TITLE
AttributeError: 'list' object has no attribute 'kmer'

### ISSUE THREAD

**Issue by francesccoll** [mgalardini/pyseer#155]
While the command below worked for previous versions of pyseer (1.3.7-dev), it failed when running pyseer version 1.3.8:

python3 pyseer-runner.py --lmm --pres efm_clade.roary.Rtab --phenotypes ATUFQXXCZQCO.pyseer.phen --phenotype-column phenotype1 --similarity efm_clade.tree_distances.csv --min-af 0.001 --print-filtered  > ATUFQXXCZQCO_1.pyseer_output.csv

Find attached the input files:
[files.zip](https://github.com/mgalardini/pyseer/files/6537621/files.zip)

I got the following message and error:

Read 493 phenotypes
Detected binary phenotype
Setting up LMM
Similarity matrix has dimension (761, 761)
Analysing 493 samples found in both phenotype and similarity matrix
h^2 = 0.00
Traceback (most recent call last):
  File "/nfs/users/nfs_f/fc4/software/latest/pyseer/pyseer-runner.py", line 8, in <module>
    main()
  File "/nfs/users/nfs_f/fc4/software/latest/pyseer/pyseer/__main__.py", line 567, in main
    options.print_samples))
  File "/nfs/users/nfs_f/fc4/software/latest/pyseer/pyseer/utils.py", line 56, in format_output
    out = '%s' % item.kmer
AttributeError: 'list' object has no attribute 'kmer'

**Comment by mgalardini** [comment]
Thanks for the report, will look into this shortly

**Comment by mgalardini** [comment]
I believe this bug was introduced in version 1.3.7, version 1.3.6 still works fine. Should have been fixed now, will likely publish a new version today
