### ISSUE TITLE
annotation of SNPs as for kmers

### ISSUE THREAD

**Issue by annarerra** [mgalardini/pyseer#167]
Hello again,

Is there a way to annotate the significant SNPs provided by pyseer as it is done with the kmers?
Or should I provide an already annotated .vcf file as input to pyseer?

Thank you in advance !!

**Comment by johnlees** [comment]
The SNPs should usually have mapped positions listed in the VCF which you can use to do this, or you can add the annotation into the VCF file and look up the p-values. We don't have a standardised way to do this, as there are too many different formats for VCFs and it's usually relatively simple to look up the positions.

If you look at this example: https://pyseer.readthedocs.io/en/master/tutorial.html#snp-and-cog-association-with-fixed-effects-model
There's an example using awk:
```
cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") \\
<(paste <(sed '1d' penicillin_SNPs.txt | cut -d "_" -f 2) \\
<(sed '1d' penicillin_SNPs.txt | cut -f 4) | \\
awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) | \\
tr ' ' '\t' > penicillin_snps.plot
```

**Comment by annarerra** [comment]
I see!

Thank you for your reply :)
