### ISSUE TITLE
recombination rate adjustment

### ISSUE THREAD

**Issue by annarerra** [mgalardini/pyseer#168]
Hello,

I would like to ask whether for a recombination rate adjustments it is necessary to use for example Gubbins before using pyseer or pyseer can take complete care of this issue.

Thank you in advance :)

**Comment by johnlees** [comment]
I'm not sure what you mean by 'recombination rate adjustment'? Perhaps you mean removing recombinant regions? In which case no, it's best not to do this before running pyseer (see e.g. https://figshare.com/articles/thesis/The_background_of_bacterial_GWAS/5550037)

**Comment by annarerra** [comment]
There is this review:  https://www.readcube.com/articles/10.3389/fmicb.2019.03119  referring to different tools for microbial GWAS and pyseer and in the beginning of the page 10 it says:
![image](https://user-images.githubusercontent.com/74925521/131501630-b442ac60-9c86-4e78-b533-c40b67d4389c.png)

**Comment by johnlees** [comment]
Ah I see. Yes, you could in theory run a recombination removal tool before calculating the patristic distances from the tree. However, gubbins and clonalframeML usually don't work too well across a whole species (there are exceptions) when GWAS has the most power, so you'd need to be careful with this. fastGEAR may be a more appropriate choice in this setting.

In my experience, when you are analysing a species with strains, getting distances with the overall distances between the strains roughly correct (or at least separated from the within-strain distances) usually does the job.
If I were you I would just run using the unadjusted tree and take a look at your QQ plot. If you're seeing inflation, then perhaps consider an adjustment for recombination on the branch lengths.

**Comment by annarerra** [comment]
Thank you for your recommendations!!

In terms of tree, in pyseer,  you have used an IQ-TREE. It has any advantage over FastTree or RAxML trees when using pyseer?

**Comment by johnlees** [comment]
I usually use fasttree as it seems to be accurate enough and is quicker. IQ-Tree + fast is also similar
See: https://wellcomeopenresearch.org/articles/3-33/v2

**Comment by annarerra** [comment]
Great!! thanks a lot for your feedback and the additional info :) 👍
