### ISSUE TITLE
unitig size

### ISSUE THREAD

**Issue by annarerra** [mgalardini/pyseer#169]
Hello,

Is there an optimal/default size for a unitig? like for kmer the 31bp?

Thank you in advance :)

**Comment by johnlees** [comment]
The size of the nodes in the DBG is the unitig size, and will be variable (minimum = k-mer length; maximum maybe be up to the genome length, but typical a few hundred bases)

Do you mean which size k-mer to build the de Bruijn graph with? In which case 31 is a reasonable default, but see the more detailed investigation in this paper: http://dx.doi.org/10.1371/journal.pgen.1007758

**Comment by mgalardini** [comment]
John beat me to it!

**Comment by annarerra** [comment]
Thank you for the answer! :)
