### ISSUE TITLE
gene annotation

### ISSUE THREAD

**Issue by annarerra** [mgalardini/pyseer#170]
Hello,

After using the --kmer mode of pyseer, i have some gene annotations like "penA|murE". I know that these features in a specific chr of N.meningitidis are close. There is any other reason for the "|" in the annotation?

Thank you in advance :)

**Comment by johnlees** [comment]
I think this just happens when multiple features are overlapping the mapped region (so when the unitig is long/genes are close):
https://github.com/mgalardini/pyseer/blob/master/pyseer/kmer_mapping/annotate_hits.py#L69

**Comment by annarerra** [comment]
Great! Thank you for the answer :)
