### ISSUE TITLE
summarised results questions

### ISSUE THREAD

**Issue by LeonardosMageiros** [mgalardini/pyseer#171]
Hi, 

I am new to pyseer and I have some questions about the summarise_annotations script that will help me understand my results better. 

In your tutorial you say that this script reports the maximum pvalue. 
Does this means that it plots the pvalue of the less significant kmer that belongs in the corresponding gene? 

If that is the case is there a way to plot the exact opposite, ie the pvalue of the most significant kmer within that gene (min pvalue)?

Could you also briefly explain what are the values avg_af	avg_maf	avg_beta?

Finally is there an easy way to have also the description of the gene along with these values? 

Thank you very much in advance for your time and help. 
Kind regards 
Leonardos

**Comment by mgalardini** [comment]
Hi,

according [to the code](https://github.com/mgalardini/pyseer/blob/master/scripts/summarise_annotations.py#L68) the reported value is the maximum -log10 of the p-value, so effectively the lowest p-value, or the most significant kmer/unitig. The other fields are the average value of `af`, `maf` and `beta` for all kmers/unitigs that map to that gene.

Regarding adding annotations, that could be a nice little addition to this script, perhaps using a GFF file as source for the annotation. Could you open a separate issue about that so we can keep track of possibly adding this in the future?

**Comment by LeonardosMageiros** [comment]
Thank you very much for the quick response. 

Do you have a section somewhere that you explain what af, maf, and beta is so I can understand their meaning?

I ll will open a new issue about the description of the genes. 

Thx a lot

**Comment by mgalardini** [comment]
af = allele frequency (between 0 and 1 depending on the frequency of the variant)
maf = minor allele frequency (between 0 and 0.5)
beta = the effect size of the variant

you can find more information in the [documentation of pyseer](https://pyseer.readthedocs.io/en/master/usage.html#output)
