### ISSUE TITLE
Generating manhattan plot

### ISSUE THREAD

**Issue by smb20200615** [mgalardini/pyseer#176]
Hi,

Is there a way to generate a manhattan plot (preferably in R or python) from the output of kmer GWAS using pyseer without using phandango? I want to see how the hits line up along the genome.

Also, how can I tell whether if a negative beta refers to case or control.

Many thanks,

**Comment by mgalardini** [comment]
Unfortunately the kmers/unitigs do not retain the information about their position in a given genome, so you first need to map them to whichever reference genome you are using
