### ISSUE TITLE
COG pvalue threshold and qq plot 

### ISSUE THREAD

**Issue by LeonardosMageiros** [mgalardini/pyseer#178]
Hi, 

I used the Rtab file from roary to run a COG analysis following the tutorial on your page.  
Nonetheless I added the --output-patterns option so I can run the count_patterns.py script to define a significance threshold. 

Is that applicable on the COG analysis? After running count_patterns.py I am left with ~3500 genes which are a lot. 
Should I just make my threshold stricter? 

Also my qq plot on the results looks very bad: 
![image](https://user-images.githubusercontent.com/28563735/138695383-349675fe-ca23-4b06-bcbb-d6ea69d46673.png)

Can it be because I have closely related isolates in my dataset? Would down sampling work better? 

Thank you in advance for your time and help. 
Best 
Leonardos

**Comment by LeonardosMageiros** [comment]
Thank you very much for your help. 

The changes you proposed improved my GWAS a lot: 

![image](https://user-images.githubusercontent.com/28563735/140300970-bdc67756-201f-42ce-b05b-00fcd079a26a.png)

If you think that this looks ok as well you can close this issue. 

Best 
Leonardos

**Comment by johnlees** [comment]
Yes, that looks a lot better to me, glad this was useful!
