### ISSUE TITLE
Error while pip3 installing pyseer

### ISSUE THREAD

**Issue by vidhya-sai** [mgalardini/pyseer#182]
Hi Marco,

While installing Pyseer, I get the following error:

Collecting glmnet_python@ https://github.com/johnlees/glmnet_python/archive/v1.0.2.zip (from pyseer==1.3.9)
Could not find a version that satisfies the requirement glmnet_python@ https://github.com/johnlees/glmnet_python/archive/v1.0.2.zip (from pyseer==1.3.9) (from versions: )
No matching distribution found for glmnet_python@ https://github.com/johnlees/glmnet_python/archive/v1.0.2.zip (from pyseer==1.3.9)

Though I have installed glmnet both manually and using pip3, it doesn't help. 

I am new here so if it has already been addressed elsewhere, could you direct me to the right link.

Thank you

**Comment by mgalardini** [comment]
We have discontinued the pypi package for this exact reason. We suggest using the conda package, which should be able to take care of installing all dependencies.

    conda create -c bioconda -n pyseer pyseer

and then

    conda activate pyseer

Hope this helps

**Comment by vidhya-sai** [comment]
Thanks, this approach worked.
