### ISSUE TITLE
Mapping kmers to single reference genome 

### ISSUE THREAD

**Issue by vidhya-sai** [mgalardini/pyseer#184]
Hi,

I tried mapping k-mers of length 21 to a single reference genome, using the following command : 

`phandango_mapper significant_kmers.txt GCF_genomic.fna result_kmer.plot`

I get the following result : 

Read 167181 k-mers
Mapped 0 k-mers (but why?)

What confuses me is that when I tried mapping k-mers of length 31 (from the same set of strains), it was able to map them to the reference genome. But for a length of 21, it's unable to map. Does it have anything to do with the length of the k-mers here? Or am I going wrong somewhere?

Thank you

**Comment by johnlees** [comment]
The mapping uses BWA (see https://github.com/mgalardini/pyseer/blob/master/pyseer/kmer_mapping/bwa.py#L37) as follows:
```
bwa index GCF_genomic.fna
bwa mem -v 1 -k 8 GCF_genomic kmers.fa
```
where the kmers.fa file can be produced by running `sed '1d' significant_kmers.txt | awk '{print ">" NR "\n" $1}'`

It may be that these settings don't work well for k=21, typically we've tested in the k=31-200 range. If they're not mapping using bwa you could either change these settings, or use the sensitive mode bowtie2 with a short seed, which can map very short sequences.
