### ISSUE TITLE
mapping snps

### ISSUE THREAD

**Issue by annarerra** [mgalardini/pyseer#185]
Hello,

there is a way to "map" or "annotate" the snps provided  by pyseer in terms of position in the different contigs as it is done for the unitigs?

Thank you in advance :)

**Comment by johnlees** [comment]
I'm not sure exactly what you mean, but I don't think so. If you are using a VCF, the ID in the output should include contig and position in the output?

**Comment by annarerra** [comment]
For the unitigs for example, after annotation for every unitig we have a colomn with this _contig:position;upstream;in;downstream_ info.

But for SNPs there is no such an "annotation" step and we have only these info:
![image](https://user-images.githubusercontent.com/74925521/151578954-15718b59-bc65-4917-bc01-2e599f411315.png)

**Comment by johnlees** [comment]
What data and file are you using as input? What command are you running here?

**Comment by annarerra** [comment]
input: phenotypes +  gene presence absence from roary + model
command: _pyseer --lmm --phenotypes {input.pheno} --pres {input.presence} --load-lmm {input.model} --cpu {threads} --output-patterns {output.patterns} --min-af 0.02 --max-af 0.98 > {output.results}`_

**Comment by johnlees** [comment]
So these are genes then, not SNPs?

**Comment by annarerra** [comment]
yeah, u are right, i am sorry
i had genes in mind and i was talking about SNPs :/

but still my question is about the position.

**Comment by annarerra** [comment]
For example if i want to do a manhattan plot, not using phandango, i would need some positions in the genome, or in a contig.
Probably is not provided by pyseer, i should do it externaly.

**Comment by johnlees** [comment]
Ah in that case, no, I'm sorry but we don't support these. Gene order varies from genome to genome, so it wouldn't be possible to output a simple summary of nearby genes. I'd recommend [panaroo](https://github.com/gtonkinhill/panaroo) for that kind of analysis.
