### ISSUE TITLE
Calculating LD post annotating significant unitig/kmer

### ISSUE THREAD

**Issue by vidhya-sai** [mgalardini/pyseer#187]
Hi,

So I used both unitigs & kmers as inputs to identify significant unitigs and kmers respectively. I could annotate them and now would like to check for Linkage disequilibrium between the annotated unitig/kmer if any. Though calculating LD isn't in Pyseer's pipeline, is there a method/tool that you would recommend? 

Thank you

**Comment by johnlees** [comment]
plink2 is pretty good: https://www.cog-genomics.org/plink/1.9/ld
Accepts many input formats, but you may need to do some wrangling to get k-mers in (including mapping them). I would also set the window size to the genome length.

It's also easy enough to calculate in e.g. R with the pres/abs vectors

**Comment by vidhya-sai** [comment]
Thankyou
