### ISSUE TITLE
Population structure based on phylogeny - rooting of tree

### ISSUE THREAD

**Issue by Vers4L** [mgalardini/pyseer#188]
Hi, 

I am currently using a phylogenetic tree to calculate the pairwise distances. However, I see that 4 bacterial strains are clearly not related to the other strains in my tree (branch lengths are much longer) even though they are the same species. This tree is based on core genome alignments and consists of 360 strains of the same bacterial species. I was wondering whether I should define these 4 strains as an outgroup and use them to root the tree. Would this highly impact the GWAS results?

**Comment by johnlees** [comment]
I am not actually sure, my intuition would be that you should probably root the tree this way, but that it's not likely to make much difference to the results. Maybe try both ways and plot the resulting p-values against one another?
