### ISSUE TITLE
How to deal with linkage in the data

### ISSUE THREAD

**Issue by martinastoycheva** [mgalardini/pyseer#192]
Hello, 

I am having problems with controlling for the population stuctre in my sample set and I was wodnering if I can get some help? I am not sure when the QQplots are good enough in order to be able to trust the p values. 

I have ran pyseer with gene presence file and a whole genome vcf. I am using a very good quality hgt free phylogeny and I have used the following command:

```
pyseer --phenotypes ${3} \
--vcf ${1} \
--similarity ../phylogeny_similarity_rooted_clonalML.tsv \
--lmm \
--cpu 8  > results/${2} 
```

I was wondering if I need to do any LD pruning prior to runing pyseer? I am asking because I noticed that if I do some LD pruning with bcftools (e.g r2=0.8, window size=1000) I can get the QQplots to lool very good: 

<img width="316" alt="image" src="https://user-images.githubusercontent.com/38460574/158391321-dd78d2fe-c9e8-4092-bbc5-b686e0e91a8d.png">

as opposed to bad before pruning:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/38460574/158391220-afab7a30-b231-4484-8457-031ed17d189b.png">

However, this approach removes most of the SNPs and makes the results very hard to interpret, and I am overall not very confident it is very good. Therefore, I was wondering if there is a standard way to overcome this issue? 

I am also wondering how this could be extended to unitigs and accessory genes? 
As my gene presence absence QQplots don't look that great either:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/38460574/158391770-93928357-6f2c-4650-9e19-af1490525542.png">

Cheers, 
Martina

**Comment by martinastoycheva** [comment]
Thanks very much for the quick response! If the p values are a but unrealible this case, would you advice to try the whole genome lasso model instead and not use p values?

**Comment by johnlees** [comment]
You can certainly try this as an alternative, though it is more focused on prediction, rather than finding causal variants.
