### ISSUE TITLE
deflated values

### ISSUE THREAD

**Issue by mac137** [mgalardini/pyseer#197]
Hi! I have been performing a GWAS using the command below. When I plot a q-q plot on the {output.associations} I get deflated p-values. R^2 is listed as 0.89. I am a bit confused as to whether I can trust this GWAS as I do get lots of hits (5852 after filtering). I know that p-value inflation is an issue but not sure how to think about deflated p-values

        pyseer --print-samples --phenotypes {input.pheno} --phenotype-column {params.col} --covariates {input.metadata} --use-covariates 2 --uncompressed --kmers {input.unitigs} --max-dimensions {params.dimensions} --lineage --lineage-file {output.lineage} --output-patterns {output.patterns} --distance {input.dist} --lmm --similarity {input.sim} --lineage-clusters {input.lineage} > {output.associations} 2> {log}

![image](https://user-images.githubusercontent.com/60878347/161480945-a52d5660-b277-44cd-8c03-0338742318b2.png)

I would appreciate any help. Thanks!

**Comment by johnlees** [comment]
What are you using as the significance threshold? I would suggest, from this QQ-plot, that there are no significant hits

**Comment by maciej-3** [comment]
Also, are you suggesting that I should ignore the significant hits after filtering because of the shape of this q-q plot or do you think there is an issue on how I am running things (e.g it is impossible to get a q-q plot like this with so many significant hits and I am likely doing something wrong)
