### ISSUE TITLE
few kmer hits in unitig GWAS

### ISSUE THREAD

**Issue by smb20200615** [mgalardini/pyseer#200]
Hello,

I used the summarise_annotation.py script on the output of my unitig GWAS (running with two covariates and and the --lineage option). I get a few hundred hits (running with ~1000 genomes). What concerns me is that in my gene hits summary table from summarise_annotation I get very low values for the "hits" column (1-50). Should I subset to remove the low kmer hits? I saw in the tutorial that your hits column had values in the hundreds so not sure if I should be worried. Could it be because the signal is at the variant level rather than gene presence absence?

Thank you!!

**Comment by johnlees** [comment]
This really all depends on your GWAS results, and I'm not sure I can answer this question generally. It doesn't sounds like there are any issues with what you've done from your description.

I'm also not sure what you mean by 'subset to remove the low kmer hits'

**Comment by smb20200615** [comment]
Thank you so much for your reply. I meant: should I trust the GWAS result less because there is only one kmer hit at that gene that is significant? I was thinking about setting a minimum threshold for the kmer hits but not sure if that would bias the result? In the plot here https://pyseer.readthedocs.io/en/master/tutorial.html for penicillin resistance I saw there 250-1000 kmers, which makes me worried about me getting only a handful of kmers

**Comment by johnlees** [comment]
It really depends on the phenotype honestly – penicillin resistance is strongly selected for and mosaic pbp variants mean there are lots of strong hits. 

In fact, this is probably far more than I would usually expect for almost anything else. Have a look at e.g. [table 1 in the original seer paper](https://www.nature.com/articles/ncomms12797/tables/1). I would say that in general having one (significant) finding in a gene is sufficient for further investigation/speculation.

**Comment by smb20200615** [comment]
Thank you so much Dr. Lees!
