### ISSUE TITLE
How to run pyseer with vcf files

### ISSUE THREAD

**Issue by sekhwal** [mgalardini/pyseer#204]
Hi,
I am trying to run pyseer with a dataset of 500 isolates of Salmonella. I have generated vcf files using snippy and merged them using bcftools. Please let me know if I can use pyseer for GWAS analysis. I am following the tutorial but not sure if a structure.tsv is necessary to run the pipeline and how to generate it. Also, I have a phenotype file (.txt) that includes sample names and sample metadata information such as blood, brain, joint (sample collection). Please let me know if I need to convert this information into binary format.

I am using the following command, please let me know if it is correct?

pyseer --phenotypes phenotypes.txt --vcf salm.vcf.gz --min-af 0.01 --max-af 0.99 --cpu 15 >pyseer_results.txt

**Comment by sekhwal** [comment]
Thank you for your answer. 
In addition, I am preparing a phenotype file that includes multiple columns with binary values. Please let me know if the pipeline works on multiple columns in the phenotype file. Here is an example.
Phenotype.txt (Example)
samples blood brain joint intestine
salm10      1      0       1        0
salm12      0      1        0       1
salm37       1      1        1      0

**Comment by mgalardini** [comment]
Yes, you can run pyseer multiple times by changing the `--phenotype-column` argument (by default the last column is used)

**Comment by sekhwal** [comment]
I am thinking if I can provide all the columns at the same time in one file. Please let me know if the pipeline works with multiple columns at one time.
I used TASSEL previously where I was able to use GLM and MLM functions (multiple variables). So, I am thinking if I can use pyseer with multiple columns.

**Comment by mgalardini** [comment]
I am afraid you can only run associations one phenotype at a time with pyseer

**Comment by sekhwal** [comment]
Can you help me suggest any pipeline for microbial gwas that can take multiple columns or is it considerable to use phenotype one by one. I am new in microbial gwas so any suggestion would be appreciated.

Thank you,
