### ISSUE TITLE
Add a script to compute a covariance matrix from unitigs presence/absence

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#206]
A reviewer for our last paper suggested to compute the LMM Kinship matrix from unitigs presence/absence patterns, so that core/accessory population structure is fully account for. Could this be useful as part of pyseer's scripts? We have it here for the moment: https://github.com/microbial-pangenomes-lab/2021_ecoli_pathogenicity/blob/main/workflow/scripts/unitigs2covar.py

**Comment by johnlees** [comment]
Yeah could certainly add this! It's also possible in fastlmm to use two kinship matrices, that might be another way of doing it

**Comment by mgalardini** [comment]
Closing this as we actually have this script already! See PR #211 for some fixes to it
