### ISSUE TITLE
pyseer running issue

### ISSUE THREAD

**Issue by sekhwal** [mgalardini/pyseer#207]
Hi,

I am trying to run pyseer with the dataset of 71. I have a core.vcf file (generated from snippy) and a mash.tsv (generated with following command at pyseer) and a phenotype file(column 1: sample name and column 2: binary values). 

However, when I run pyseer using following command it shows an message ("Multiple alleles at NC_003210_417483. Skipping") and don't generate any association data in output file.:

pyseer --phenotypes phenotype.txt --vcf core.vcf --distances mash.tsv --min-af 0.01 --max-af 0.99 --cpu 15 --filter-pvalue 1E-8 > pyseer.assoc

error: message:
Multiple alleles at NC_003210_417483. Skipping

Generate mash file:

mash sketch -s 10000 -o mash_sketch assemblies/*.fa
mash dist mash_sketch.msh mash_sketch.msh| square_mash > mash.tsv

**Comment by johnlees** [comment]
Firstly, I'd suggest following these: https://pyseer.readthedocs.io/en/master/best_practices.html
Secondly, try removing `--filter-pvalue`.
Also, please could you share the full output of the program?

**Comment by sekhwal** [comment]
Hi,

I removed the --filter-pvalue and got the results. However, in the running
process it showed the messages (attached screenshot)  and finally generated
the results. Please see the attached screenshot and a result file. Could
you please let me know how to eliminate the messages.
I am following the pyseer tutorial and further it suggests COGs analysis
and also it is suggesting k-mer association. Could you please let me know
do I need to perform COGs analysis and k-mer based association as well or
the --vcf that I am using is sufficient. I am trying to make a manhattan
plot using the pyseer.assoc file.


 pyseer.assoc
<https://drive.google.com/file/d/1wbrddanuHAIIZkCbRAB920wprBJbWtSD/view?usp=drive_web>
Thank you,

Manoj

**Comment by sekhwal** [comment]
Yes, I am using COGs analysis. 

First, I generated distance matrix using the command:
mash sketch -s 10000 -o mash_sketch assemblies/*.fasta
mash dist mash_sketch.msh mash_sketch.msh| square_mash > mash.tsv

second: I am using COGs analysis with the following command: 

pyseer --phenotypes phenotype.txt --pres gene_presence_absence.Rtab --distances mash.tsv --save-m mash_mds --max-dimensions 8 > listeria_COGs.txt

It generates results files (COGs.txt and .pkl)  with the message:
No observations of fhs1_2 in selected samples

Next, I am running the below command, it generates the results file also but I am not getting how to interpret the association with my phenotype data (brain and non-brain) in Manhattan plot. Are the highest peaks associated with phenotype that has binary value 1. 
pyseer --phenotypes resistances.pheno --vcf snps.vcf.gz --load-m mash_mds.pkl --lineage --print-samples > penicillin_SNPs.txt

**Comment by sekhwal** [comment]
I am trying to run K-mer association. Is K-mer association separate from COGs analysis.

**Comment by johnlees** [comment]
> It generates results files (COGs.txt and .pkl) with the message:
> No observations of fhs1_2 in selected samples

Either your sample names don't match between the three input files, or that specific gene isn't present in any passing samples

> Are the highest peaks associated with phenotype that has binary value 1.

Yes, but possibly negatively associated. See the sign of the effect size

> Is K-mer association separate from COGs analysis.

Yes


Overall, it might also be helpful to read further on some microbial GWAS background:
https://www.nature.com/articles/nrg.2016.132
https://figshare.com/articles/thesis/The_background_of_bacterial_GWAS/5550037/1
https://www.nature.com/articles/nrmicro.2016.82
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007758

**Comment by sekhwal** [comment]
I tried pipeline with k-mer association, as following the pyseer GWAS module. In the results, it shows no-significant variables in the significant_kmers.txt. Is there any way to improve the results to get significant variables?

**Comment by johnlees** [comment]
Not really I'm afraid! Add more samples probably -- 71 is very small for this kind of trait

**Comment by sekhwal** [comment]
Thank you for the clarification. I can see a peak of my results at
phandango. However, I am not getting your comment "See the sign of the
effect size". Where can I find the sign of the effect size?
If you are able to find the attachment, please see the phandango result
image.

In addition, I am trying to run the pipeline with the k-mer association
also.
