### ISSUE TITLE
qq plot

### ISSUE THREAD

**Issue by littlejoseph22** [mgalardini/pyseer#212]
![微信图片_20220625131038](https://user-images.githubusercontent.com/101612154/175759352-0627604b-6fd0-4088-a9de-d5fa357ffce3.jpg)
![微信图片_20220625131053](https://user-images.githubusercontent.com/101612154/175759353-6baaa9dd-0f6a-4061-8e52-9b78c63b21f2.jpg)
qq plot is so strange. I ran several copies of different data, but the output qq plot is similar to this. The scripts I use are all qq_plot.py

**Comment by johnlees** [comment]
Can you try making the qq plot from the p-values in something else (e.g. https://rdrr.io/bioc/GWASTools/man/qqPlot.html)
Are they logged/unlogged?

**Comment by mgalardini** [comment]
Another user had a similar issue with the script (issue #197). I think the problem is the precision on the x-axis possibly? We could just comment this line I think https://github.com/mgalardini/pyseer/blob/master/scripts/qq_plot.py#L52

**Comment by julibeg** [comment]
just came across this as well (and [this question](https://stackoverflow.com/questions/71210319/labels-inverted-in-statsmodels-qq-plot-in-python)). Looks like `sm.qqplot_2samples` takes the data to be plotted on the x-axis as first argument and the data for the y-axis as second. I don't know if this was different in the past, but in the script, `y` is passed before `x`. Could this be the issue?

**Comment by julibeg** [comment]
ok, looks like this is definitely an issue in the statsmodels function. With an older statsmodels version (0.12.2) I get this plot:
![qq_plot](https://user-images.githubusercontent.com/37619875/177207857-746963ed-ea74-4108-b041-05a0b52296d8.png)

With the current version (0.13.2), however, I get this:
![qq_plot](https://user-images.githubusercontent.com/37619875/177208027-a9886abe-0448-42fa-9d7f-523482af21f9.png)

**Comment by julibeg** [comment]
Can confirm that swapping `x` and `y` indeed restored the original behaviour for me.

**Comment by mgalardini** [comment]
Ah thanks that makes sense. I guess we'll have to check statsmodels's version and change the behavior accordingly.

**Comment by mgalardini** [comment]
[This](https://github.com/statsmodels/statsmodels/commit/5dcec847571b4b121573ddc2474095563f254cbb) seems the relevant commit, so checking for version 0.13 and below could catch this
