### ISSUE TITLE
ValueError: could not convert string to float error in mash dist mash_sketch.msh mash_sketch.msh| square_mash > mash.tsv

### ISSUE THREAD

**Issue by Albertzhuo123** [mgalardini/pyseer#215]
HELLO!
   when I running 
   mash sketch -s 10000 -o mash_sketch assemblies/*.fa
   mash dist mash_sketch.msh mash_sketch.msh| square_mash > mash.tsv 
   it report error "Traceback (most recent call last):
  File "/home/z/miniconda3/bin/square_mash", line 8, in <module>
    sys.exit(main())
  File "/home/z/miniconda3/lib/python3.8/site-packages/pyseer/mash.py", line 38, in main
    dist = float(dist)
ValueError: could not convert string to float: 'assemblies/AP006725.1.2004.China.hv.fa'
"
I do not know how to solve it.

the log is:
Sketching assemblies/AP006725.1.2004.China.hv.fa...
Sketching assemblies/CP009208.1.2000.USA.hv.fa...
Sketching assemblies/CP012426.2014.Singapore.kp.fa...
Sketching assemblies/CP012560.2014.USA.kp.fa...
Sketching assemblies/CP012561.2014.USA.kp.fa...
Sketching assemblies/CP012568.2015.USA.kp.fa...
Sketching assemblies/CP012745.2013.Greece.kp.fa...
Sketching assemblies/CP014647.2013.USA.kp.fa...
Sketching assemblies/CP014755.1.2016.USA.kp.fa...
Sketching assemblies/CP014762.2014.USA.kp.fa...
Sketching assemblies/CP015025.2013.USA.kp.fa...
Sketching assemblies/CP015130.2014.USA.kp.fa...
Sketching assemblies/CP015134.1.2016.USA.kp.fa...
Sketching assemblies/CP015382.2016.USA.kp.fa...
Sketching assemblies/CP015385.2016.USA.kp.fa...
Sketching assemblies/CP015392.2016.USA.kp.fa...
Sketching assemblies/CP015500.1.2015.PDR.fa...
Sketching assemblies/CP015500.2015.UAE.kp.fa...
Sketching assemblies/CP015753.2014.beijing.kp.fa...
Sketching assemblies/CP015822.1.2010.Switzerland.kp.fa...
Sketching assemblies/CP015990.1.2016.hangzhou.kp.fa...
Sketching assemblies/CP016159.2014.beijing.kp.fa...
Sketching assemblies/CP016811.2010.USA.kp.fa...
Sketching assemblies/CP016813.2006.taiwan.kp.fa...
Sketching assemblies/CP016923.2013.USA.kp.fa...
Sketching assemblies/CP016926.2014.USA.kp.fa...
Sketching assemblies/CP017385.2007.taiwan.kp.fa...
Sketching assemblies/CP017934.1.2007.USA.kp.fa...
Sketching assemblies/CP018140.1.2013.Germany.kp.fa...
Sketching assemblies/CP018337.2014.Germany.kp.fa...
Sketching assemblies/CP018352.2011.USA.kp.fa...
Sketching assemblies/CP018356.2011.USA.kp.fa...
Sketching assemblies/CP018364.2015.Germany.kp.fa...
Sketching assemblies/CP018427.2012.USA.kp.fa...
Sketching assemblies/CP018428.2013.USA.kp.fa...
Sketching assemblies/CP018437.2012.USA.kp.fa...
Sketching assemblies/CP018438.2013.Germany.kp.fa...
Sketching assemblies/CP018447.2013.Germany.kp.fa...
Sketching assemblies/CP018450.2013.Germany.kp.fa...
Sketching assemblies/CP018454.2015.china.kp.fa...
Sketching assemblies/CP018458.2014.Germany.kp.fa...
Sketching assemblies/CP018671.1.2008.USA.kp.fa...
Sketching assemblies/CP018676.2010.USA.kp.fa...
Sketching assemblies/CP018686.2014.Germany.kp.fa...
Sketching assemblies/CP018692.2014.Germany.kp.fa...
Sketching assemblies/CP018695.2014.Germany.kp.fa...
Sketching assemblies/CP018701.2014.Germany.kp.fa...
Sketching assemblies/CP018707.2014.Germany.kp.fa...
Sketching assemblies/CP018713.2014.Germany.kp.fa...
Sketching assemblies/CP018719.2014.Germany.kp.fa...
Sketching assemblies/CP018735.2013.Germany.kp.fa...
Sketching assemblies/CP018816.1.2016.USA.kp.fa...
Sketching assemblies/CP019219.2004.taiwan.kp.fa...
Sketching assemblies/CP023134.2.2017.UK.hv.fa...
Sketching assemblies/CP023722.1.2014.tanwai.hv.fa...
Sketching assemblies/CP027036.1.2013.ST11.XDR.fa...
Sketching assemblies/CP027042.1.2013.ST147.XDR.fa...
Sketching assemblies/CP027048.1.2012.ST258.XDR.fa...
Sketching assemblies/CP027053.1.2012.ST258.XDR.fa...
Sketching assemblies/CP031562.1.2018.XDR.fa...
Sketching assemblies/CP034415.1.2016.shandong.crhv.fa...
Sketching assemblies/CP035383.1.2017.nanchang.hv.fa...
Sketching assemblies/CP040533.1.2016.China.hv.fa...
Sketching assemblies/CP040539.1.2016.China.hv.fa...
Sketching assemblies/CP040545.1.2016.China.hv.fa...
Sketching assemblies/CP041022.1.2015.taiwan.STNA.hv.fa...
Sketching assemblies/CP041022.1.2015.taiwan.hv.fa...
Sketching assemblies/CP041353.2.2018.China.hv.fa...
Sketching assemblies/CP041373.1.2018.PDR.fa...
Sketching assemblies/CP042977.1.2017.anhui.hv.fa...
Sketching assemblies/CP043669.1.2018.China.STNA.hv.fa...
Sketching assemblies/CP043670.1.2018.China.STNA.hv.fa...
Sketching assemblies/CP043670.1.2018.China.hv.fa...
Sketching assemblies/CP054720_1.fa...
Sketching assemblies/CP054726_1.fa...
Sketching assemblies/CP054732_1.fa...
Sketching assemblies/CP054738_1.fa...
Sketching assemblies/CP054744_1.fa...
Sketching assemblies/CP054750_1.fa...
Sketching assemblies/CP054756_1.fa...
Sketching assemblies/CP054762_1.fa...
Sketching assemblies/CP054768_1.fa...
Sketching assemblies/CP054774_1.fa...
Sketching assemblies/CP054780_1.fa...
Sketching assemblies/CP061053.1.2015.XDR.fa...
Sketching assemblies/CP061062.1.2015.XDR.fa...
Sketching assemblies/CP064205_1.fa...
Sketching assemblies/CP064208_1.fa...
Sketching assemblies/CP064211_1.fa...
Sketching assemblies/CP064217_1.fa...
Sketching assemblies/CP064223_1.fa...
Sketching assemblies/CP064229_1.fa...
Sketching assemblies/CP064232_1.fa...
Sketching assemblies/CP064235_1.fa...
Sketching assemblies/CP064241_1.fa...
Sketching assemblies/CP064246_1.fa...
Sketching assemblies/CP064252_1.fa...
Sketching assemblies/CP064258_1.fa...
Sketching assemblies/CP091326_1.fa...
Sketching assemblies/CP091330_1.fa...
Sketching assemblies/CP092717_1.fa...
Sketching assemblies/NC_009648.2006.USA.kp.fa...
Sketching assemblies/NC_011283.1.2008.USA.kp.fa...
Sketching assemblies/NC_017540.2011.Korea.kp.fa...
Sketching assemblies/NC_022082.1.2010.hanghzhou.kp.fa...
Sketching assemblies/NC_022566.1.2013.China.hv.fa...
Sketching assemblies/NZ_CP003999.2011.Brazil.kp.fa...
Sketching assemblies/NZ_CP006659.2.2013.USA.kp.fa...
Sketching assemblies/NZ_CP006722.2002.taiwan.kp.fa...
Sketching assemblies/NZ_CP006738.2013.taiwan.kp.fa...
Sketching assemblies/NZ_CP006798.2013.USA.kp.fa...
Sketching assemblies/NZ_CP006918.2010.USA.kp.fa...
Sketching assemblies/NZ_CP007727.2011.USA.kp.fa...
Sketching assemblies/NZ_CP007731.2012.USA.kp.fa...
Sketching assemblies/NZ_CP008797.2012.USA.kp.fa...
Sketching assemblies/NZ_CP008827.2011.USA.kp.fa...
Sketching assemblies/NZ_CP008831.2012.USA.kp.fa...
Sketching assemblies/NZ_CP008929.2011.Nepal.kp.fa...
Sketching assemblies/NZ_CP009114.2012.USA.kp.fa...
Sketching assemblies/NZ_CP009461.2013.hangzhou.kp.fa...
Sketching assemblies/NZ_CP009771.2013.USA.kp.fa...
Sketching assemblies/NZ_CP009775.2013.USA.kp.fa...
Sketching assemblies/NZ_CP009863.2013.USA.kp.fa...
Sketching assemblies/NZ_CP009872.2013.USA.kp.fa...
Sketching assemblies/NZ_CP009876.2013.USA.kp.fa...
Sketching assemblies/NZ_CP010361.1.2010.USA.kp.fa...
Sketching assemblies/NZ_CP010392.1.2011.USA.kp.fa...
Sketching assemblies/NZ_CP011313.1.2011.Germany.kp.fa...
Sketching assemblies/NZ_CP011578.2011.USA.kp.fa...
Sketching assemblies/NZ_CP011624.1.2010.USA.kp.fa...
Sketching assemblies/NZ_CP011647.2012.USA.kp.fa...
Sketching assemblies/NZ_CP011976.2013.USA.kp.fa...
Sketching assemblies/NZ_CP011980.2015.USA.kp.fa...
Sketching assemblies/NZ_CP011985.2015.USA.kp.fa...
Sketching assemblies/NZ_CP011989.2013.USA.kp.fa...
Sketching assemblies/NZ_CP012300.2013.hongkong.kp.fa...
Sketching assemblies/NZ_CP012743.2011.Greece.kp.fa...
Sketching assemblies/NZ_CP012744.2013.Greece.kp.fa...
Sketching assemblies/NZ_CP012753.2013.Korea.kp.fa...
Sketching assemblies/NZ_CP012883.2013.Australia.kp.fa...
Sketching assemblies/NZ_CP012987.2013.Canada.kp.fa...
Sketching assemblies/NZ_CP012992.2013.Canada.kp.fa...
Sketching assemblies/NZ_CP013322.2010.USA.kp.fa...
Sketching assemblies/NZ_CP013711.2014.harbin.kp.fa...
Sketching assemblies/NZ_CP014004.2014.jiangxi.kp.fa...
Sketching assemblies/NZ_CP014008.1.2014.shanghai.hv.fa...
Sketching assemblies/NZ_CP014008.2014.shanghai.kp.fa...
Sketching assemblies/NZ_CP015500.1.2015.PDR.fa...
Sketching assemblies/NZ_CP019047.1.2015.shanghai.hv.fa...
Sketching assemblies/NZ_CP020061.1.2017Submitted.USA.kp.fa...
Sketching assemblies/NZ_CP020498.1.2012.USA.kp.fa...
Sketching assemblies/NZ_CP022023.1.kp.fa...
Sketching assemblies/NZ_CP022691.2.2012.Australia.kp.fa...
Sketching assemblies/NZ_CP022997.1.2013.Ningbo.kp.fa...
Sketching assemblies/NZ_CP023722.1.2014.taiwan.STNA.hv.fa...
Sketching assemblies/NZ_CP024707.1.2014.beijing.crhv.fa...
Sketching assemblies/NZ_CP025951.1.2015.China.kp.fa...
Sketching assemblies/NZ_CP026495.1.2009.Iran.kp.fa...
Sketching assemblies/NZ_CP027189.1.2008.China.kp.fa...
Sketching assemblies/NZ_CP028176.1.2012.Germany.kp.fa...
Sketching assemblies/NZ_CP028716.1.2017.China.kp.fa...
Sketching assemblies/NZ_CP028816.1.2012.Spain.kp.fa...
Sketching assemblies/NZ_CP030269.1.2015.China.crhv.fa...
Sketching assemblies/NZ_CP032240.1.2018.Shanghai.kp.fa...
Sketching assemblies/NZ_CP034082_1.fa...
Sketching assemblies/NZ_CP034415.1.2016.shandong.crhv.fa...
Sketching assemblies/NZ_CP034420.1.2016.beijing.crhv.fa...
Sketching assemblies/NZ_CP034778.1.2018.Canada.hv.fa...
Sketching assemblies/NZ_CP035194.1.2012.Laos.kp.fa...
Sketching assemblies/NZ_CP035196.1.2012.Laos.kp.fa...
Sketching assemblies/NZ_CP035383.1.2017.nanchang.hv.fa...
Sketching assemblies/NZ_CP037742.12016.USA.hv.fa...
Sketching assemblies/NZ_CP037928.1.2017.Italy.kp.fa...
Sketching assemblies/NZ_CP040533.1.2016.China.hv.fa...
Sketching assemblies/NZ_CP040539.1.2016.China.hv.fa...
Sketching assemblies/NZ_CP040545.1.2016.beijing.hv.fa...
Sketching assemblies/NZ_CP041022.1.2015.tanwai.STNA.hv.fa...
Sketching assemblies/NZ_CP041022.1.2015.tanwai.hv.fa...
Sketching assemblies/NZ_CP041023.1.2015.taiwan.hv.fa...
Sketching assemblies/NZ_CP041373.1.2018.PDR.fa...
Sketching assemblies/NZ_CP042977.1.2017.anhui.hv.fa...
Sketching assemblies/NZ_CP045193.1.2018.China.kp.fa...
Sketching assemblies/NZ_CP045674.1.2018.China.kp.fa...
Sketching assemblies/NZ_CP045694.1.2013.USA.STNA.hv.fa...
Sketching assemblies/NZ_CP045694.1.2013.USA.hv.fa...
Sketching assemblies/NZ_CP046381.1.2017.Bangladesh.kp.fa...
Sketching assemblies/NZ_CP046612.1.2016.china.kp.fa...
Sketching assemblies/NZ_CP047160.1.2019.China.kp.fa...
Sketching assemblies/NZ_CP047192.1.2019.Shanghai.kp.fa...
Sketching assemblies/NZ_CP050822.1.2017.jiangsu.STNA.hv.fa...
Sketching assemblies/NZ_CP050822.1.2017.jiangsu.hv.fa...
Sketching assemblies/NZ_CP050826.1.2018.anhui.hv.fa...
Sketching assemblies/NZ_CP050829.1.2019.shandong.hv.fa...
Sketching assemblies/NZ_CP050834.1.2018.jiangxi.hv.fa...
Sketching assemblies/NZ_CP050840.1.2018.shandong.hv.fa...
Sketching assemblies/NZ_CP050843.1 .2018.hebei.hv.fa...
Sketching assemblies/NZ_CP050845.1.2018.heilongjiang.hv.fa...
Sketching assemblies/NZ_CP052036.1.2016.China.hv.fa...
Sketching assemblies/NZ_CP054063.1.2019.wuxi.hv.fa...
Sketching assemblies/NZ_CP054720_1.fa...
Sketching assemblies/NZ_CP054726_1.fa...
Sketching assemblies/NZ_CP054732_1.fa...
Sketching assemblies/NZ_CP054738_1.fa...
Sketching assemblies/NZ_CP054744_1.fa...
Sketching assemblies/NZ_CP054750_1.fa...
Sketching assemblies/NZ_CP054756_1.fa...
Sketching assemblies/NZ_CP054762_1.fa...
Sketching assemblies/NZ_CP054768_1.fa...
Sketching assemblies/NZ_CP054774_1.fa...
Sketching assemblies/NZ_CP054780_1.fa...
Sketching assemblies/NZ_CP064205_1.fa...
Sketching assemblies/NZ_CP064208_1.fa...
Sketching assemblies/NZ_CP064211_1.fa...
Sketching assemblies/NZ_CP064217_1.fa...
Sketching assemblies/NZ_CP064223_1.fa...
Sketching assemblies/NZ_CP064229_1.fa...
Sketching assemblies/NZ_CP064232_1.fa...
Sketching assemblies/NZ_CP064235_1.fa...
Sketching assemblies/NZ_CP064241_1.fa...
Sketching assemblies/NZ_CP064246_1.fa...
Sketching assemblies/NZ_CP064252_1.fa...
Sketching assemblies/NZ_CP064258_1.fa...
Sketching assemblies/NZ_CP091326_1.fa...
Sketching assemblies/NZ_CP091330_1.fa...
Sketching assemblies/NZ_CP092717_1.fa...
Sketching assemblies/Reference.fa...
Writing to mash_sketch.msh...
Traceback (most recent call last):
  File "/home/z/miniconda3/bin/square_mash", line 8, in <module>
    sys.exit(main())
  File "/home/z/miniconda3/lib/python3.8/site-packages/pyseer/mash.py", line 38, in main
    dist = float(dist)
ValueError: could not convert string to float: 'assemblies/AP006725.1.2004.China.hv.fa'

**Comment by mgalardini** [comment]
Hi, which version of pyseer are you using? Try `pyseer --version`. Also,
can you paste here the output of the following command: `mash dist
mash_sketch.msh mash_sketch.msh | head`

Thanks

**Comment by Albertzhuo123** [comment]
newest
1.3.10.

**Comment by mgalardini** [comment]
And can you paste here the output of `mash dist mash_sketch.msh mash_sketch.msh | head`?

**Comment by Albertzhuo123** [comment]
yes,wait for me please

**Comment by Albertzhuo123** [comment]
assemblies/AP006725.1.2004.China.hv.fa	assemblies/AP006725.1.2004.China.hv.fa	00	10000/10000
assemblies/CP009208.1.2000.USA.hv.fa	assemblies/AP006725.1.2004.China.hv.fa	0.00924152	0	7001/10000
assemblies/CP012426.2014.Singapore.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0105133	0	6693/10000
assemblies/CP012560.2014.USA.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.00999991	0	6815/10000
assemblies/CP012561.2014.USA.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0099916	0	6817/10000
assemblies/CP012568.2015.USA.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0100082	0	6813/10000
assemblies/CP012745.2013.Greece.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0105645	0	6681/10000
assemblies/CP014647.2013.USA.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0107621	0	6635/10000
assemblies/CP014755.1.2016.USA.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0100957	0	6792/10000
assemblies/CP014762.2014.USA.kp.fa	assemblies/AP006725.1.2004.China.hv.fa	0.0103943	0	6721/10000

**Comment by mgalardini** [comment]
Can't see anything wrong at a first glance; perhaps you have one of the filenames with the fasta sequences with a space in its name?

**Comment by Albertzhuo123** [comment]
NOW I trying to do GWAS study with "--no-distances".
IT STILL REPORT ERROR 
the log and vcf file,pheno file is updated.
thanks for your help!
[update_for_github.tar.zip](https://github.com/mgalardini/pyseer/files/9244368/update_for_github.tar.zip)

**Comment by mgalardini** [comment]
Closing for lack of new information
