### ISSUE TITLE
Adding multidimensionality to cmdscale

### ISSUE THREAD

**Issue by BernardoOlisan** [mgalardini/pyseer#217]
This is more a recommendation than an error.

So I used the classical MDS function [cmdscale](https://pyseer.readthedocs.io/en/master/_modules/pyseer/cmdscale.html) and noticed that it only outputs 2d vectors, is going to output that bc the np function like `np.diag` only accepts 1D or 2D and outputs 2D, it would be nice to support multidimensionality in this function, like...

`def cmdscale(D, ndim)`

I also tried to look for alternatives to np.diag that accepts a p-dimension, but didn't find something:/

**Comment by johnlees** [comment]
Thanks for the suggestion, but we aren't actively developing that model any more, and suggest use of the linear mixed model instead.
