### ISSUE TITLE
Covariates on binary phenotypes lead to very different results

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#22]
There might be something going on here: to begin with pyseer outputs only 50 kmers, versus 174 of seer. pyseer is reporting an lrt-pvalue of 1 for all 50 kmers, while seer is reporting more realistic values. Any idea what the cause might be? I might have missed something on how the covariates are handled?

Commands used:

`seer -k kmers.gz -p subset.pheno --struct all_structure_new --covar_file covariates.txt --covar_list 2q,3 --pval 1 --chisq 1`

`pyseer kmers.gz subset.pheno distances.tsv --filter-pvalue 1 --lrt-pvalue 1 --max-dimensions 3 --covariates covariates.txt --use-covariates 2q 3`

**Comment by mgalardini** [comment]
Great! I'll test it right away!

**Comment by mgalardini** [comment]
It looks like we are making lots of progress, but the lrt-pvalues diverge quite a bit in some cases

![image](https://user-images.githubusercontent.com/1125215/32570358-e4579c4c-c491-11e7-94e7-e9ad7efbfbba.png)

The betas are also diverging quite a bit, so maybe not a bug?

![image](https://user-images.githubusercontent.com/1125215/32570465-2c2c170a-c492-11e7-927b-63d6707a4db9.png)

**Comment by johnlees** [comment]
I think these are the Firth cases, which are triggered much more regularly
on this small set (so the ones with bad-chisq)? The Firth LRT in seer is
wrong if so, which explains the similar betas but different p-values.

**Comment by mgalardini** [comment]
Great then!
