### ISSUE TITLE
similarity_pyseer generates a matrix with all 0's

### ISSUE THREAD

**Issue by AmayAgrawal** [mgalardini/pyseer#220]
Hi,

I want to use `-lmm` to perform GWAS using the linear mixed models. As the `-lmm` option requires similarity matrix, I saw that there is an option `similarity_pyseer` which can calculate this similarity matrix. I used this option as follows `similarity_pyseer --vcf my_vcf_file.vcf samples.txt > genotype_kinship.tsv` to calculate the similarity matrix, but the output matrix generated by this contains all 0's in it and then when I use this matrix to perform GWAS using `-lmm`, it gives the following error `Invalid similarity matrix. Did you use --calc-C?`

Can you please help me with this?

**Comment by mgalardini** [comment]
Could you share your VCF file please?

**Comment by AmayAgrawal** [comment]
[variants.zip](https://github.com/mgalardini/pyseer/files/10067958/variants.zip)

**Comment by mgalardini** [comment]
Using pyseer 1.3.10 I get a normal looking similarity matrix (see attached):

```
$ similarity_pyseer --version
similarity 1.3.10
```

`similarity_pyseer --vcf variants.vcf samples.txt > similarity.tsv`

[similarity.tsv.gz](https://github.com/mgalardini/pyseer/files/10068052/similarity.tsv.gz)
[samples.txt.gz](https://github.com/mgalardini/pyseer/files/10068053/samples.txt.gz)

Did you use all samples for your run?

**Comment by AmayAgrawal** [comment]
I tried the .tsv file that you uploaded to run the GWAS and it works now. I am using the same version of similarity_pyseer (1.3.10)

Yes, I used all samples to construct the similarity matrix. Is it here that I am doing anything wrong?

**Comment by mgalardini** [comment]
Not that I can see: can you try to run `similarity_pyseer --vcf variants.vcf samples.txt > similarity.tsv` with the `samples.txt` file I attached above? Closing the issue anyway, I would say there's no bug that I can see
