### ISSUE TITLE
Evaluate the results

### ISSUE THREAD

**Issue by AlperYurtseven** [mgalardini/pyseer#221]
Hi,
We have run Pyseer Linear Mix models using vcf files for GWAS and now we want to extract significant variant.
Currently we used lrt-pvalue column and took 10 most significant variants with lowest lrt-pvalue
But we are not sure if it is the right way to get significant hits. Should we consider another column? What would be your suggestions?
Thank you in advance!

**Comment by johnlees** [comment]
lrt-pvalue is the correct column. It is probably sensible to use a Bonferroni adjustment and look at a QQ-plot. These are covered in the second part of the k-mer/LMM tutorial: https://pyseer.readthedocs.io/en/master/tutorial.html#k-mer-association-with-mixed-effects-model

**Comment by AlperYurtseven** [comment]
Thank you so much!
