### ISSUE TITLE
QQ plot graphs

### ISSUE THREAD

**Issue by AlperYurtseven** [mgalardini/pyseer#222]
Hi,
After following the tutorial, we have ended up having qq plots like this for our data.
What can we interpret from these two graphs? 
![qq_plot](https://user-images.githubusercontent.com/49569516/204549423-991a4280-ebb5-4473-a352-1291d745444b.png)
![qq_plot (1)](https://user-images.githubusercontent.com/49569516/204549433-7fa1c013-2853-4406-8230-e520c203716f.png)
Thank you in advance

**Comment by johnlees** [comment]
From the documentation:
> When interpreting this plot, check that it is well controlled at low p-values and doesn’t show any large ‘shelves’ symptomatic of poorly controlled confounding population structure. Although this plot is far above the null (as indeed, there are many k-mers associated with penicillin resistance), the p-values up to 0.01 are as expected which is what we’re after.

These look ok to me
