### ISSUE TITLE
GWAS analysis using both SNP and COG together

### ISSUE THREAD

**Issue by AmayAgrawal** [mgalardini/pyseer#224]
Hi,

I want to run a GWAS study using both the SNP's data as well as the gene presence absence data. I know that I can run them individually with `--vcf` and `--pres` option, but I was wondering if I can run them together because I want to get the significant hits out of the whole combined SNP's and gene presence data using bonferroni correction. Or it will be the same thing if I run them individually and then combine the significant hits from both of them?

**Comment by johnlees** [comment]
> Or it will be the same thing if I run them individually and then combine the significant hits from both of them?

Yes, do this. It probably makes sense to use a single correction/number of tests based on the number of independent genetic blocks – I'd maybe just use number of SNP patterns for both
