### ISSUE TITLE
Getting error while installing pyseer using miniconda

### ISSUE THREAD

**Issue by dzjian2** [mgalardini/pyseer#225]
Hi Marco,

I am a new Miniconda user that needs to use pyseer to perform a GWAS study in regards to a bioinformatic pipeline. After downloading 64-bit Miniconda on Windows 11, I first created a new environment (bioinformatics3) and added the necessary channels according to pyseer documentation.

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install pyseer

However, when I try running the installation command, it always ends up looking something like:

(bioinformatics3) C:\Users\djian>conda install pyseer
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes. Press CTRL-C to abort.
failed

UnsatisfiableError:

I have already tried running this a couple of times, uninstalling and reinstalling, trying it out on another computer and using other suggested commands anaconda has for installing pyseer as well, but still no luck. Someone has suggested that this is because bioconda does not support windows.
 Any insight/solutions would be amazing and please note that I am a new Conda user with virtually no background in Python/command line since I only am familiar with R. Thank you and please let me know if I can clarify anything!

**Comment by johnlees** [comment]
This package isn't available for Windows, and indeed no bioconda packages are built for Windows.

Can I suggest that you try running using Linux instead. You can easily do this within Windows by using Windows Subsystem for Linux: https://learn.microsoft.com/en-us/windows/wsl/install
