### ISSUE TITLE
Do the tree for calculating the kinship matrix should be rooted?

### ISSUE THREAD

**Issue by Tonny-zhou** [mgalardini/pyseer#226]
Dear author,

Thank you very much for this GWAS tool! I have a small question, i.e., the core-genome phylogenetic tree used for calculating the kinship matrix (by the phylogeny_distance.py script) should be previously rooted (midpointed rooted or using outgroup etc.)? or we could use the  unroot tree to calculate the kinship matrix?

Yours,
Trump

**Comment by johnlees** [comment]
I usually midpoint root it (there's an option in the script for this), but it will depend on your dataset. Have a look at the QQ plot to confirm control is as expected
