### ISSUE TITLE
VCF input requires bgzip and tabix index

### ISSUE THREAD

**Issue by LeahRoberts** [mgalardini/pyseer#229]
I ran into an error running pyseer with VCF input:

```
File "pysam/libcbcf.pyx", line 4466, in pysam.libcbcf.VariantFile.fetch
ValueError: fetch requires an index
```

We realised it was because my VCF was not bgzipped (and indexed). Running bgzip and tabix fixed this error. I'm not sure if there was something in the docs I missed about this file format requirement, but might be nice to implement this (or check for it) within pyseer.

**Comment by mgalardini** [comment]
Thanks for pointing this out. Might be worth mentioning it in the docs, though giving a more informative error message should be something the pysam library should do
