### ISSUE TITLE
Add to bioconda

### ISSUE THREAD

**Issue by johnlees** [mgalardini/pyseer#23]
Once the current issues are closed I'd say we'd have a good version to add to bioconda

**Comment by mgalardini** [comment]
Agreed! Are you familiar with the process? I could look into that otherwise...

**Comment by mgalardini** [comment]
On a side note, we should also make it installable through `pip`

**Comment by johnlees** [comment]
I got some of the way there with the original seer, and I think it would be easier with python so I'm happy to look into it.
I don't have any experience with `pip` but that sounds like a good idea too.

**Comment by mgalardini** [comment]
Got the pip installation sorted; I'll be in charge of tagging versions and uploading them whenever we introduce significant changes.

**Comment by mgalardini** [comment]
I was thinking that since `pip` is installed in anaconda, there is no real reason to add `pyseer` to it. I will close this for the moment...
