### ISSUE TITLE
Problem installing pyseer with conda

### ISSUE THREAD

**Issue by ireneortega** [mgalardini/pyseer#232]
I create a new environment I run: `conda install -c bioconda pyseer
`
The package is not installed after these messages appear:

```
(pyseer_env) $ conda install -c bioconda pyseer
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: -
```

I tried with conda install pyseer I got the same. With pip after downloading the repository I got other errors which I can't solve. How can I install with conda?

**Comment by mgalardini** [comment]
So, the first method has not thrown an error, have you tried waiting for it to finish?

**Comment by ireneortega** [comment]
Yes, it shows me `(pyseer_env)` $ again to run a new command. I tried with different computers and I always get the same.

**Comment by mgalardini** [comment]
Are you sure you are not getting any other message other than what you reported? Also, if you have bioconda in your channels already it's much faster not to specify it, so doing something like `conda create -n pyseer pysser` should be faster

**Comment by johnlees** [comment]
Two other tips:
- Install into a clean conda environment and make sure you haven't installed anything else into your base environment
- Use mamba instead of conda
