### ISSUE TITLE
vcf GT format:0/0, 1/1 or 0 , 1

### ISSUE THREAD

**Issue by yayahoho1** [mgalardini/pyseer#241]
Hi,
   i am using pyseer to do GWAS analysis in bacteria.  But i am not sure whether the vcf GT format would make a difference to the result? 
The vcf file was generated from snippy sofware.

tkanks in advance !

**Comment by johnlees** [comment]
The code for this is here: https://github.com/mgalardini/pyseer/blob/master/pyseer/input.py#L445-L490
See the comment on lines 471-474:
>               # This is dominant encoding. Any instance of '1' will count as present
>               # Could change to additive, summing instances, or reccessive only counting
>               # when all instances are 1.
>               # Shouldn't matter for bacteria, but some people call hets

So any 1 in the GT field should count as present

**Comment by xqzangnolan** [comment]
Hi, i am using pyseer to do GWAS analysis in bacteria, but my input SNP.VCF seems not correct. 
when i run: 

`pyseer --phenotypes Genes.phenotype --vcf core.vcf.gz --load-m 1mash_mds.pkl --lineage --print-samples > 1_SNPs.txt*`*


Read 441 phenotypes
Detected binary phenotype
Loaded projection with dimension (441, 344)
Analysing 441 samples found in both phenotype and structure matrix
Writing lineage effects to lineage_effects.txt
Traceback (most recent call last):
  File "/home/**i/anaconda3/envs/pyseer/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/**/anaconda3/envs/pyseer/lib/python3.10/site-packages/pyseer/__main__.py", line 468, in main
    infile, sample_order = open_variant_file(var_type, var_file, options.burden, burden_regions, options.uncompressed)
  File "/home/**/anaconda3/envs/pyseer/lib/python3.10/site-packages/pyseer/input.py", line 278, in open_variant_file
    infile = VariantFile(var_file)
  File "pysam/libcbcf.pyx", line 4117, in pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4380, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 514, in pysam.libchtslib.HTSFile.tell
NotImplementedError: seek not implemented in files compressed by method 1


could you recommend a good way to prepare the SNP.VCF as an input file for Pyseer? Thanks a lot!

**Comment by mgalardini** [comment]
these commands should compress and index your vcf file correctly:

```
bgzip file.vcf
tabix -p vcf file.vcf.g
```z

**Comment by mgalardini** [comment]
Closed due to inactivity
