### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#25]
It would be nice to refactor the code so that it becomes a proper python package, which will definitely improve things for future additions.

I suggest to follow the ideas exposed here: https://gehrcke.de/2014/02/distributing-a-python-command-line-application/

I can look into it whenever I've got some free time.

**Comment by johnlees** [comment]
That would be good. If you're planning on doing that I'll hold off on
feature additions for now to avoid massive merge conflicts

**Comment by mgalardini** [comment]
I should be able to implement this in a fairly reasonable amount of time, hopefully this week. I'll update you if I can't find the time...

**Comment by mgalardini** [comment]
Done, now `pyseer` looks like a proper python package. Should be easier to implement new features now and eventually add proper unit tests.
