### ISSUE TITLE
burden testing, gene length

### ISSUE THREAD

**Issue by dustinlong** [mgalardini/pyseer#250]
Is there any adjustment for gene length (kernel size) in the burden testing function? For example, would the following cases result in equivalent outputs?

2 non-synonymous mutations in cases and 0 non-synonymous mutations, in controls in a gene 10000 bases long
2 non-synonymous mutations in the same cases and 0 non-synonymous mutations in the same controls, in a gene 100 bases long

Thank you!

Dustin

**Comment by johnlees** [comment]
Good question – no there is not adjustment, these cases would be identical. We don't count the number of mutations, any observation of even a single mutation causes a count of '1'. The burden test is therefore designed more for rare loss of function variants which are strongly expected to have the same effect on the gene (frameshift, early stop etc). For more sophisticated analyses with non-syn variants perhaps something like SKAT might be better

**Comment by dustinlong** [comment]
Thank you for the quick response--very helpful to know!

Dustin
