### ISSUE TITLE
Annotating Kmers in RNA regions

### ISSUE THREAD

**Issue by idolawoye** [mgalardini/pyseer#253]
Hi @mgalardini. I am trying to annotate kmers that are associated with drug resistance and some of the regions with high p-values are in the 16S rRNA which is visible from the Manhanttan plot. However, when I proceed to annotate the kmers, it doesn't show this region as it only annotates regions in genes.
Is there a way we can include RNA annotation in this output?

**Comment by mgalardini** [comment]
Thanks for bringing this up; I have [created a branch](https://github.com/mgalardini/pyseer/tree/issue_253) with a new option for the `annotate_hits_pyseer` script. If you are able to download it locally you can test it by adding the `--feature-type rRNA --feature-type tRNA` options. I have tested it on our own test data but would be good to have an external validation.

**Comment by mgalardini** [comment]
that tells me that you are still using the version you have installed. to test this new script you can follow the link, download the source, `cd` into it and then run `python3 annotate_hits_pyseer-runner.py` followed by your arguments. that should force python to use the locally downloaded version

**Comment by idolawoye** [comment]
Thanks a lot. It worked. I now have the rRNA annotated in the output :)
