### ISSUE TITLE
Getting Intergenic regions, sRNAs and ORF from pyseer

### ISSUE THREAD

**Issue by AbubakariAbdulwasid** [mgalardini/pyseer#262]
Hi Sir, please I have done GWAS using the three genetic variants (SNPs, unitigs and gene presence or absence) and want to locate  Intergenic regions, sRNAs and ORF from my GWas. Is there a way to do that?

**Comment by mgalardini** [comment]
Hi, you can follow the tutorial for some hints into doing what you describe (i.e. annotating your hits): [interpreting significant k-mers](https://pyseer.readthedocs.io/en/master/tutorial.html#interpreting-significant-k-mers). You want to look into the `annotate_hits_pyseer` command, optionally including a few different `--feature-type` arguments

**Comment by AbubakariAbdulwasid** [comment]
when I use "./annotate_hits_pyseer-runner.py significant_Unitigs2.txt Annotating_unitigs.txt annotated_unitigs_VP_Ref_RIMD2.txt --feature-type CDS --feature-type sRNA --feature-type intergenic --feature-type ORF, this is the message I got  annotate_hits_pyseer-runner.py script does not directly support the --feature-type option for sRNA  intergenic ORF

**Comment by mgalardini** [comment]
Are you sure you have a recent version of pyseer? [You can download the latest one](https://github.com/mgalardini/pyseer/releases/tag/1.3.11), for which the option should be available. Another thing to mention is that you should check your GFF files to make sure the feature type you want to look for is in there; the feature type is the third column

**Comment by mgalardini** [comment]
Closed due to inactivity
