### ISSUE TITLE
"UnsatisfiableError" when trying to install pyseer with conda

### ISSUE THREAD

**Issue by dennisdharmawan** [mgalardini/pyseer#263]
Hello, I am trying to use `conda install pyseer` in a new, empty conda environment, and the following error occurred:
```
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                            

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==12.2.1=0
  - pyseer -> matplotlib-base -> __osx[version='>=10.9']

Your installed version is: 12.2.1
```
I am using Mac OS Monterrey (12.2.1) on a Macbook Air (M1 chip) and I have matplotlib 3.8.0 installed in my base conda environment. Is this not compatible with pyseer?

**Comment by johnlees** [comment]
Although pyseer itself is architecture independent (noarch), many of the pyseer dependencies don't have `osx-arm64` packages (which is what your M1 chip runs).

You'll need to use the following workaround to create an `osx-64` environment, which will work: https://conda-forge.org/docs/user/tipsandtricks/#installing-apple-intel-packages-on-apple-silicon

**Comment by dennisdharmawan** [comment]
Thank you, it worked!

Also to anyone seeing this whose "Solving environment" took forever like me, there's a chance that your default solver is still the classic one instead of the faster `conda-libmamba-solver` (https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community). I had to use this in order to successfully install pyseer.
