### ISSUE TITLE
merged snps files

### ISSUE THREAD

**Issue by akarkaba** [mgalardini/pyseer#266]
The out put of snps.vcf of nullabor pipeline is within directory of each file, however the output is of such 
##bcftools_viewCommand=view --include '(GT="1/1" || GT="1|1") && INFO/DP>=0 && AF>=0' snps.raw.vcf; Date=Tue Oct 24 23:32:02 2023
##bcftools_annotateVersion=1.9+htslib-1.9
##bcftools_annotateCommand=annotate --remove ^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AF,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL; Date=Tue Oct 24 23:32:02 2023
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	snippy
NC_002953.3	987	.	G	T	8046.03	.	AF=1;AO=230;DP=231;QA=9019;QR=22;RO=1;TYPE=snp	GT:DP:RO:QR:AO:QA:GL	1/1:231:1:22:230:9019:-808.974,-67.338,0

When merging several files to run the following 
pyseer --phenotypes resistances.pheno --vcf snps.vcf.gz --load-m mash_mds.pkl --lineage --print-samples > penicillin_SNPs.txt

Errors appearing 
I think its either with the merging or pyseer not happy with the current format?

**Comment by mgalardini** [comment]
Hi, could you be more specific with the errors you are seeing please?

**Comment by mgalardini** [comment]
Closed due to inactivity
