### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#27]
I have a few unit tests made already, but it's probably best to address "version 2" so that some work doesn't get duplicated.

@johnlees would you have some VCFs and .RTab files I can play with? Thanks!

**Comment by johnlees** [comment]
Yeah, that makes sense!
As far as version 2 goes, for the main pyseer I've got two further commits which will add new models, whereas the rest of the changes will be new scripts. So once I've added those two changes that would be a good time to think about unit tests.

I've attached some new example data here that I have been testing VCF, Rtab input and burden testing with.
[new_examples.tar.gz](https://github.com/mgalardini/pyseer/files/1507135/new_examples.tar.gz)

**Comment by mgalardini** [comment]
Great! I'll write the tests that are not likely to change and wait for the rest! Thanks a lot!

**Comment by johnlees** [comment]
Complete in version 2 now (thanks!) - shall we close this?

**Comment by mgalardini** [comment]
Absolutely! There are a few things that could be tested better (including the fastLMM code), but we definitely covered most of the code!
