### ISSUE TITLE
Setting Semi-Quantitative Phenotypes for MIC Analysis in Pyseer

### ISSUE THREAD

**Issue by OtakuZerg** [mgalardini/pyseer#282]
Dear All,

I am reaching out to see if anyone has experience using Pyseer to analyze semi-quantitative phenotype values. Specifically, I am looking to analyze Minimum Inhibitory Concentration (MIC) levels and would like to set continuous values for my key phenotype.

The MIC levels I am working with include values such as <2, 2, 4, ..., 32, >32.

Thank you in advance for any insights or guidance you can share!

Best regards,
George

**Comment by johnlees** [comment]
Have a look here: https://www.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.001222

Probably best to code them as continuous values for now

**Comment by OtakuZerg** [comment]
@johnlees 
Thank you so much
