### ISSUE TITLE
Distances used for population structure estimation

### ISSUE THREAD

**Issue by cizydorczyk** [mgalardini/pyseer#31]
Hello,

With regard to the distance matrix used in the fixed effects analysis, is there anything specific about the distance matrices calculated using mash or the patristic distances from a phylogenetic tree for the pyseer models to work? ie. does this have to be a distance matrix calculated using mash (estimated Jaccard distance) or one containing patristic distances?

Or are these distances interchangeable, and this could be a distance matrix calculated using one of the classical evolutionary models, such as the Jukes-Cantor or F84 models?

Any response is much appreciated!

Thank you,
Conrad Izydorczyk

**Comment by johnlees** [comment]
Hi Conrad,
You can use any distance you want, we've suggested mash for speed and convenience, and patristic distances as in some cases these may be more accurate. I'd expect there is little difference between results from different distance matrices (based on _S. pneumoniae_). JC, F84 etc models should work just fine too, as long as the sample names are listed in a header for each column, and for each row. I think seaview gives basically this format, or you can get it from `dist.dna` and `write.table` in R.
Cheers,
John
