### ISSUE TITLE
Phandango script

### ISSUE THREAD

**Issue by rafarios50** [mgalardini/pyseer#35]
I would like to plot in phandango the mapped kmers to my reference which were associated to given lineages. An I used the phandango_mapper script to do so, but I wasnt able to find a way to map the results in the .plot file to the kmers file.

Is there any identification for the mapped kmers, or a table for the kmer and in which position it was mapped in the reference to be able to identify the relationship to the lineage?

Thanks,

**Comment by johnlees** [comment]
Hi,
I've added to the phandango_mapper script so an extra file is produced, which will list the lineage for each entry in the `.plot` file. 

It's on the `v1_fixes` branch for now, so you'll have to clone the repository and checkout that branch, or copy the file (https://github.com/mgalardini/pyseer/blob/e0ee3c39600923358d41adaa6fd4aaa5c49a23a8/pyseer/kmer_mapping/phandango_plot.py), if you want to use it before we merge into master at some point in the future.

Hope that helps!
John
