### ISSUE TITLE
Lineage association question

### ISSUE THREAD

**Issue by rafarios50** [mgalardini/pyseer#37]
Good day,

I wanted to know if some results that Im obtain, and which wasnt expected could be fine or if there might be some issu with my approach and use of pyseer.

I have a set of isolates already classified into 5 different populations (lineages) of different sizes (number of isolates).

And wanted to know if there were some kmers associated to the lineage, which could explain why the populations were different.

To do so I used fms-lite to count the kmers and mash to obtain the distance matrix. Then I did 5 different analysis, one for each population, setting the pheno file with 1 if that isolate belonged to the queried population (case) and 0 if not (control), using the lineage option, given the labels for each population and forcing the use of continuous phenotype (as binary would perfectly separate the data and no regression was done).

In each experiment, the lineage_effects.txt file associated the corresponded population as the most important to the phenotype (expected result). But when looking into the kmers, in one case, there were no kmers related to the population.

My question is: What could be happening there that no kmer was found to be associated to the expected population, something that didnt happen to the other experiments?

Thank you,

**Comment by johnlees** [comment]
Hi,

Thanks for your question, and interest in the software.

One reason this might be happening is that including the distances in the regression removes the lineage signal, which in your case is that you're looking for. Using the `--lineage` option I think then includes the lineages twice, and the regressions may not be done.

I think the best way to run this analysis would be not to use `--distances`, and then just look at the k-mers with significant `lrt-p-val` for each of your five analyses.
Although at the moment we force this argument to be included. You could use a dummy distance matrix of all 1s and set `--max-dimensions` to 1 (a hack), or if that won't work I can add an option to turn off the distance check.

Cheers,
John

**Comment by rafarios50** [comment]
Ok, will do that,

Thanks

**Comment by johnlees** [comment]
I just noticed that I'd also noted that I need to add this option in #34 so will add this soon

**Comment by johnlees** [comment]
This options will be merged soon, or you can use it now by checking out the `v1_fixes` branch

**Comment by rafarios50** [comment]
Thank you for the fix, but unfortunately, it didnt work with my data.

After filtering the kmers accordingly to the threshold by the count_patterns.py script, no kmer was found to be related to the lineage im interested in.

Wouldn't it mean that this lineage is characterized as not having the other kmers associated to the other lineages (something like an inverse proportion)? Would it be possible to conclude that with this kind of analysis?

**Comment by rafarios50** [comment]
I checked on the total list of kmers, without any filtering, for any associated to the lineage im interested in, and no single one was associated to it, but there were kmers associated to the other lineages. Which I think is weird because in the lineage_effects.txt file, the lineage Im interested had a p-value of zero and a weld test value higher than the others and with a very big number (5E15), meaning it was the most associated to itself.

How can I know if the analysis might have stopped for some reason?, it looks like it finished fine.

What do you mean by a small lineage? The total sample has 340 genomes and that lineage contains 101 of them, dont know if that count as small.

Thanks,

**Comment by rafarios50** [comment]
This was the command line that i used, i didnt download the fix, but rather used the hack you mentioned, where the all_distances_1.tsv is just a matrix of only 1.

pyseer --phenotypes metadata.pheno --kmers output.txt.gz --distances all_distances_1.tsv --min-af 0.01 --max-af 0.99 --filter-pvalue 1E-8 --lineage --print-samples --lineage-clusters isolates_clades_noheader.txt --continuous --max-dimensions 1 > pyseer_out_clinicalred_dist1_lineages.txt

After that executed:
python count_patterns.py pyseer_out_clinicalred_dist1_lineages.txt

And found:
Patterns:       8416260
Threshold:      5.94E-09

And to select the kmers that passed the threshold from count_patterns.py:
cat <(head -6 pyseer_out_clinicalred_dist1_lineages.txt) <(awk '$4<5.94E-09 {print $0}' pyseer_out_clinicalred_dist1_lineages.txt) > significant_kmers_clinicalred_dist1_lineages.txt

Not sure if the threshold i need to low is the one used in pyseer, or the one used to select the kmers at the end.

Thanks,

**Comment by johnlees** [comment]
Just to check, the final column of `metadata.pheno` has the samples in the lineage as 1, and outside of the lineage as 0?

I would suggest downloading the fix (`pip install --upgrade pyseer`), and trying:
```
pyseer --phenotypes metadata.pheno --kmers output.txt.gz --no-distances --min-af 0.01 --max-af 0.99 --print-samples --continuous > pyseer_out_clinicalred_dist1_lineages.txt
```
Then selecting significant k-mers as before.

This is in case the hack with the distance is messing anything up. The way you are running the analysis means the `--lineage` options aren't needed.

**Comment by rafarios50** [comment]
Ill check and re do it, but another question:

How would i pick the kmers related to the lineage if that column will not appear in the output file but the principal component most associated to that kmer instead? How could i know which principal component is most associated to the lineage, in this case the phenotype?

**Comment by rafarios50** [comment]
I understand what you mean about redundancy.

I might not been able to ask  correctly, but more plainly, and explain myself a little bit on why im doing the separate experiments.

I first tried to include all lineages, given them values from 0 to 5 in the pheno file and then the lineage option to identify the kmers most associated to each lineage and in this case, the discarded lineage was the one that is not showing any related kmers. I wasnt able to understand the output. And thus tried to run it separately for each lineage independently. 

When running the lineages independently, the output will have one kmer per row, and after the filtering, can i assume that those kmers passing the filters will be the ones most related to the lineage/phenotype without need to look for other information in the output file?

Im asking that, because, when using the lineage effect and using the lineage-cluster option (with a file with one sample per line with the lineage it belongs to), each kmer will have the lineage column with the name of the lineage that kmer was most associated to, which was easy to interprete.
In the lineage im troubled with, there no kmers with the name of the lineage i was interested in, not that the output file was empty with no kmers at all.

I dont want to find the PC most associated to the lineage through all kmers, just the kmers so i can look after the genes those kmers are mapping to.

Not sure if this makes things clearer or make them worst.

**Comment by johnlees** [comment]
I think I understand better now. I would run as noted in my comment above (https://github.com/mgalardini/pyseer/issues/37#issuecomment-393581542), though you may no longer need `--continuous`. Format your `metadata.pheno` file as follows:
```
samples lineage_1 lineage_2 lineage_3 lineage_4 lineage_5
s1 0 1 0 0 0
s2 1 0 0 0 0
s3 0 0 0 0 1
```
In this example s1 is in lineage 2, s2 in lineage 1 and s3 in lineage 5. Run five times, using `--phenotype-column` values 2-6. The output files will then contain k-mers significantly associated with these lineages.

**Comment by rafarios50** [comment]
Thanks, It is running now.

The output file from each run will have the kmers associated to the column in the pheno file used to do the run, is that correct?

**Comment by johnlees** [comment]
Yes, that's right
