### ISSUE TITLE
Add tests and CI

### ISSUE THREAD

**Issue by johnlees** [mgalardini/pyseer#4]

**Comment by mgalardini** [comment]
This is probably related to machine-specific stuff and definitely on the Firth regression. If I run the tests on our cluster I get results that are somehow different. Below I'm reporting the Pearson's correlation between my "baseline" and the one we I got on our cluster:

```
af      1.000
filter-pvalue   1.000
lrt-pvalue      0.863
beta    0.967
beta-std-err    1.000
intercept       0.676
PC1     -0.731
PC2     0.977
PC3     0.984
PC4     0.968
PC5     0.997
PC6     1.000
PC7     0.917
PC8     0.998
PC9     0.975
PC10    0.991
```

For now I'll adapt the tests to only fail if the correlation drops below 0.9. It has to do with the Firth regression, as if I exclude those I'm getting perfect correlation. Do you think that there is any way to make the results more deterministic?

**Comment by mgalardini** [comment]
Nevermind, I generated the baseline with in a different branch, sorry to cause confusion!

**Comment by johnlees** [comment]
If you still get it, could be due to the use of the pseudoinverse (`np.linalg.pinv`) which drops elements based on a machine specific tolerance I think.
