### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by samlipworth** [mgalardini/pyseer#50]
Thanks for making this which looks awesome - I've spent a few days playing with it but have a few issues:  firstly when running with kmers the programme runs fine but finds no significant kmers - I 26/87 samples witht the phenotype of interes, is my analysis underpowered?  I know that real relevant SNPs exist from heuristic analysis but pyseer fails to find these - I'm not sure what's going wrong?

Secondly when attempting to use the output of roary gene_presence_abscence.Rtab, I get the error: 
Read 87 phenotypes
Detected binary phenotype
Setting up LMM
Similarity matrix has dimension (87, 87)
Analysing 87 samples found in both phenotype and similarity matrix
ValueError: Unexpected mismatch between header and data row.

I think the Rtab file is fine (I've checked it in R) and I'm using the same phenotype file as before.  Do you have any idea what is causing this?

**Comment by mgalardini** [comment]
Hi,

sorry to hear you are encountering problems; is the kmer harboring the SNP
having a low p-value despite being not significant?

Regarding the error with the .tab file, would you mind sending it over so
that I can have a look?

Thanks,
Marco

**Comment by johnlees** [comment]
A common error that leads to this can be different sample names in the pheno/struct file (looks like they match in the above) and the variant file. Do the samples have the same names in the Rtab/kmer file and the phenotype file?

I'm shortly going to make a small update to warn in these cases

**Comment by samlipworth** [comment]
Thanks for getting back to me Marco.  The only thing printed to stdout is
the headings (ie I din't even get any non-significant kmers), I'm just
re-running again now so I can reproduce the exact error message.  Files
attached - I think they do match.

**Comment by samlipworth** [comment]
output is as follows:
Read 87 phenotypes
Detected binary phenotype
Setting up LMM
Similarity matrix has dimension (87, 87)
Analysing 87 samples found in both phenotype and similarity matrix
h^2 = 0.00
40204093 loaded variants
7384 filtered variants
40196709 tested variants
0 printed variants
