### ISSUE TITLE
Problem with using multi-threading?

### ISSUE THREAD

**Issue by flashton2003** [mgalardini/pyseer#51]
I'm using pyseer on Ubuntu 16.04, within a conda env running python3.7.

The below crash happens at the same point on multiple runs, the output file has reached 3.6 GB (it's the same size to the byte when it throws the error).

Any thoughts?

```(py37) ubuntu@ashton-pyseer:~/crypto/seer/data/2018.09.05$ pyseer --phenotypes 2018.08.01.pyseer.phenotypes.sanger_corrected.txt --kmers fsm_kmers.txt.gz --cpu 4 --distances 2018.09.05.alive_dead.tsv --min-af 0.01 --max-af 0.99 > pyseer.nofilt2.assoc
Read 744 phenotypes
Detected binary phenotype
Structure matrix has dimension (448, 448)
Analysing 448 samples found in both phenotype and structure matrix
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/py37/lib/python3.7/site-packages/pyseer/input.py", line 476, in iter_variants
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/py37/bin/pyseer", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda2/envs/py37/lib/python3.7/site-packages/pyseer/__main__.py", line 450, in main
    options.cpu*options.block_size))
  File "/home/ubuntu/anaconda2/envs/py37/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/ubuntu/anaconda2/envs/py37/lib/python3.7/multiprocessing/pool.py", line 383, in _map_async
    iterable = list(iterable)
RuntimeError: generator raised StopIteration
```

**Comment by mgalardini** [comment]
Hi Phil,

sorry to hear that; can you confirm that this only happens with multiple CPUs? And could you give us some more details on which kind of variants are you using (kmers, vcf, roary's rtab) and how many of them are there? If this happens consistently I'm thinking that it may be due to a particular variant behaving weirdly or a corner case we are not handling well. Happy to also have a look at the data myself if you are willing to share it.

Best,
Marco

**Comment by flashton2003** [comment]
Hi Marco,

Sorry, I should have included the command line in the initial report 🤦‍♂️ 
`pyseer --phenotypes 2018.08.01.pyseer.phenotypes.sanger_corrected.txt --kmers fsm_kmers.txt.gz --cpu 4 --distances 2018.09.05.alive_dead.tsv --min-af 0.01 --max-af 0.99 > pyseer.nofilt2.assoc`

There are 7014569 kmers.

I haven't run it with one CPU, it takes some time (6-8 hours I think) to crash with 4 CPUs. I just thought that might be the issue due to the traceback.

Will slack you the files 😄 

Phil

**Comment by johnlees** [comment]
I wonder if this is being triggered once all the k-mers have been read
('next' raises StopIteration when None is returned - which is dealt with by
'for' as used with a single core, but may not be by starmap?). Do you know
whether it looks like this might be the case? What k-mer line number does
the final k-mer in the output pyseer.nofilt2.assoc correspond to?

Cheers,
John

**Comment by mgalardini** [comment]
Hi Phil,

I've tried your data but I was not able to reproduce the error; could you tell us what the last variant in the `pyseer.nofilt2.assoc` file is? If it corresponds to `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT` then I'd say that you encountered a nasty error with no consequences.

Best,
M

**Comment by Morteza-M-Saber** [comment]
I had the same problem. Apparently the problem originates from python 3.7 itself and not from pyseer.
Downgrading to python 3.6, solved the problem.

**Comment by mgalardini** [comment]
Ah, that's interesting! I'll have a try with the newest python and see what happens then...

**Comment by mgalardini** [comment]
The latest commit should fix the issue, although I should mention that the error message was always happening at the very end of the run, therefore not affecting results in any way. Thanks both for reporting it!

**Comment by flashton2003** [comment]
Thanks for the fix, sorry to be uncommunicative. This issue has been sitting in my inbox the whole time making me feel guilty if that's any consolation to you.
