### ISSUE TITLE
Handle missing data in VCF and Rtab files

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#53]
I was made aware of the fact that we are considering `.` entries in VCFs as the variant being absent instead of uncalled. I think this should be changed to meet users' expectations. While we are at it it could good to add this feature to Rtab files, as some people use the format to encode their own data such as CNVs. Should be relatively easy, I will try a fix soon.

**Comment by johnlees** [comment]
One thing to consider here is that in a strict sense p-values aren't comparable when using different sample sizes. If making this change it might be an idea to also add a filter on maximum number of missing values to minimise this effect

**Comment by mgalardini** [comment]
Ah, that's a very good point; I'll try to find a way to parametrize that and potentially to add a new message in the notes
