### ISSUE TITLE
installation testing

### ISSUE THREAD

**Issue by ChrisHIV** [mgalardini/pyseer#59]
Hi guys, the test installation instructions say
Run unit tests:  
`pytest -v tests`  
Test functions and output:  
`cd tests/ && bash run_test.sh && cd ../`  
Can you clarify in what directory these commands should be run? If installed via a git clone it's fairly obvious; if via pip or conda it's not...
Cheers
Chris

**Comment by johnlees** [comment]
Hi Chris,
Sorry this is unclear. As far as I can tell the conda package (and pip?) doesn't install the test directory - we rely on travisCI (both our own, and the bioconda setup) to run those tests for each commit/release.
If you'd like to test locally I think you need to use the git repo directly.
Hope that helps,
John

**Comment by ChrisHIV** [comment]
Roger!

**Comment by ChrisHIV** [comment]
Possibly related: the tutorial mentions running scripts in the `scripts/` directory. Are these also only available through the git repo?

**Comment by ChrisHIV** [comment]
Sorry clicked on reopen by mistake, meant to just comment.
Something else from the tutorial: it mentions running the command 'similarity', which is not found after my conda installation.
Also, trivial thing - the phandango_mapper script thinks that it is called phandango_plot (as seen by calling it with no args).

**Comment by mgalardini** [comment]
Hi,

yes, the `scripts` directory is not included in the installation and should be downloaded from the repository. We could add a note to make it more explicit.

You are right about the similarity script: it's currently not installed and we should probably fix that: for now you can download the `similarity-runner.py` script in the root of the repository and type: `python3 similarity-runner.py -h`.

Thanks for spotting this,
M

**Comment by johnlees** [comment]
I'll update the recipes now!

**Comment by johnlees** [comment]
@mgalardini shall we make a release for 1.2.0?

**Comment by mgalardini** [comment]
Yes we definitely should! Let me add a bare minimum number of command line tests for enet and I'll publish the new version...
