### ISSUE TITLE
SyntaxError: Non-ASCII character

### ISSUE THREAD

**Issue by ChrisHIV** [mgalardini/pyseer#60]
Hi guys,
On both my laptop and my cluster, git clone followed by `python pyseer-runner.py` gives  
```Traceback (most recent call last):
  File "pyseer-runner.py", line 5, in <module>
    from pyseer.__main__ import main
  File "/home/chris/pyseer/pyseer/__main__.py", line 45, in <module>
    from .enet import load_all_vars
  File "/home/chris/pyseer/pyseer/enet.py", line 174
SyntaxError: Non-ASCII character '\xc2' in file /home/chris/pyseer/pyseer/enet.py on line 174, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```
Any ideas?
Cheers
Chris

**Comment by johnlees** [comment]
This is due to a ± symbol I included in a recent merge. I think this should be ok on python 3 - are you using python 2? I'll change it to +/- to avoid this though

**Comment by johnlees** [comment]
I couldn't reproduce this right away, but hopefully 9c2c12c0371299f011bb972f01425841a58de6a1 fixes it. Please reopen the issue if not!
Cheers,
John

**Comment by ChrisHIV** [comment]
Thanks that got rid of that error. Other errors though, I think due to the mess I've got my python installations into...
