### ISSUE TITLE
Option for multiple chromosomes when remapping kmers

### ISSUE THREAD

**Issue by dsarov** [mgalardini/pyseer#63]
Hi,
Would it be possible to implement use of multiple chromosome assemblies/species when mapping kmers back to a reference genome? I'm working with a species that has two chromosomes and currently the second chromosome appears to be ignored in the phandango_mapper step (or at least not output in the plot files). Apologies if this is an error on my part and this is already supported.

Thanks,

Derek

**Comment by johnlees** [comment]
Hi Derek,

I think phandango, when there are multiple chromosomes or contigs, needs the genome coordinate to be continuous i.e. as if the 1st co-ordinate of the first base on the 2nd chromosome = length(chr1) + 1.
At the moment I think the output of the script would lose track of the chromosome, and start plotting these from 1 again, overlapping them on the plot.
I can make this work, and will do so when I get a chance.

Cheers,
John

**Comment by dsarov** [comment]
Hi John,

Oh awesome, that works brilliantly! I'm not overly familiar with Phandango so didn't realise that was what it was wanting.

Cheers,

Derek
