### ISSUE TITLE
bwa mapping with draft references

### ISSUE THREAD

**Issue by johnlees** [mgalardini/pyseer#64]
Problem is perhaps with multiple contigs
e.g.
```
Draft reference 1
Traceback (most recent call last):
  File "/usr/local/bin/annotate_hits_pyseer", line 9, in <module>
    load_entry_point('pyseer==1.1.2', 'console_scripts', 'annotate_hits_pyseer')()
  File "/usr/local/lib/python3.5/dist-packages/pyseer/kmer_mapping/annotate_hits.py", line 182, in main
    down_genes = extract_genes(sorted_query.closest(b=ref_annotation, s=False, D="ref", id=True, stream=True))
  File "/usr/local/lib/python3.5/dist-packages/pyseer/kmer_mapping/annotate_hits.py", line 55, in extract_genes
    for tag in match.fields[15].split(";"):
IndexError: list index out of range
```
or
```
Draft reference 1
Traceback (most recent call last):
  File "/usr/local/bin/annotate_hits_pyseer", line 9, in <module>
    load_entry_point('pyseer==1.1.2', 'console_scripts', 'annotate_hits_pyseer')()
  File "/usr/local/lib/python3.5/dist-packages/pyseer/kmer_mapping/annotate_hits.py", line 158, in main
    for mapping, kmer_line in zip(mapped_kmers, seer_remaining):
  File "/usr/local/lib/python3.5/dist-packages/pyseer/kmer_mapping/bwa.py", line 117, in bwa_iter
    (contig, pos) = hit.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```
Example files attached
[bwa_issue.tar.gz](https://github.com/mgalardini/pyseer/files/2680852/bwa_issue.tar.gz)

**Comment by SumeetTiwari07** [comment]
Hi Johnlee,
I also encountered the same error and when i looked into the sam file i found it may be because of this kind of data in bam file as shown below:
EM	0	10	23	*
EM	91	100	22	*
EM	3	13	28	*
EM	0	12	57	*
Since as per the the bwa.py script it was mentioned to split up at "**:**" and the condition is getting false and raising the valueerror.

**Comment by johnlees** [comment]
Ah great, thanks for finding that. I'll try and update this soon to at least catch the error

**Comment by SumeetTiwari07** [comment]
For your information when i used the phylogenetic tree after removing the recombination using ClonalframeML and re-run the whole analysis the above error didn't occur.

**Comment by nickp60** [comment]
Hi, so sorry to revive this but I think I'm getting the same error, even with version 1.3.5.

```
$ pyseer --version
pyseer 1.3.5
$ pyseer --phenotypes mobile_phenotypes_pyseer_kmer --phenotype-column A --kmers fsm-kmers.txt.gz --no-distances --output-patterns kmer_patterns.txt --cpu 24 > pyseer_kmers.txt
$ annotate_hits_pyseer pyseer_kmers.txt references.txt annotation.txt

[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -v 1 -k 8 MG1655.fna /mnt/shared/scratch/nw42839/2020-04-30-mobile-pyseer/mobile_gwas/pyseer_kmers/anno/remaining_kmers.fa
[main] Real time: 0.772 sec; CPU: 0.760 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
999 kmers remain
Reference 1
Traceback (most recent call last):
  File "/mnt/shared/scratch/synology/nw42839/apps/conda/envs/newpyseer/bin/annotate_hits_pyseer", line 10, in <module>
    sys.exit(main())
  File "/mnt/shared/scratch/synology/nw42839/apps/conda/envs/newpyseer/lib/python3.6/site-packages/pyseer/kmer_mapping/annotate_hits.py", line 156, in main
    for mapping, kmer_line in zip(mapped_kmers, seer_remaining):
  File "/mnt/shared/scratch/synology/nw42839/apps/conda/envs/newpyseer/lib/python3.6/site-packages/pyseer/kmer_mapping/bwa.py", line 131, in bwa_iter
    (contig, pos) = hit.split(":")
ValueError: not enough values to unpack (expected 2, got 1)
```

Do I have a misformatted file somewhere?  The reference has a single sequence, and I've tried with two others.

The attached data is an example using just the first 1000 lines of the kmers file
[mobile_gwas.zip](https://github.com/mgalardini/pyseer/files/4598314/mobile_gwas.zip)

**Comment by mgalardini** [comment]
Hi, thanks for reporting this, I'll have a look soon

**Comment by mgalardini** [comment]
Hi, I think I found the source of this crash, which is due to `bwa fastmap` not reporting k-mers with more than 20 hits (see here: https://bioinformatics.stackexchange.com/a/13052/123). I've increased it to 100 and if a k-mer has even more hits we are going to skip it and report a warning message.

**Comment by mgalardini** [comment]
You can dowload the latest master and try yourself to see if the error got fixed? Thanks!

**Comment by mgalardini** [comment]
Glad to hear this is now fixed! As a side effect it might have broken the summarise script. I'll have a look soon, thanks for reporting it.
