### ISSUE TITLE
Generator raised stop-iteration

### ISSUE THREAD

**Issue by Morteza-M-Saber** [mgalardini/pyseer#65]
Hi, I have installed pyseer on python 3.7 and running the program, terminates premature, produces output including the  analysis for  only half of the variants with the following error:

Read 2997 phenotypes
Detected binary phenotype
Structure matrix has dimension (3000, 3000)
Analysing 2997 samples found in both phenotype and structure matrix
Traceback (most recent call last):
  File "Sim/lib/python3.7/site-packages/pyseer/input.py", line 479, in iter_variants
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Sim/bin/pyseer", line 11, in <module>
    sys.exit(main())
  File "Sim/lib/python3.7/site-packages/pyseer/__main__.py", line 453, in main
    options.cpu*options.block_size))
  File "python/3.7.0/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "python/3.7.0/lib/python3.7/multiprocessing/pool.py", line 383, in _map_async
    iterable = list(iterable)
RuntimeError: generator raised StopIteration

**Comment by mgalardini** [comment]
Hi, could you provide some more information on this issue? It might be a duplicate of #51, solved by [this commit](05756bef60fe794727816024247d6825120d8b1e).

**Comment by Morteza-M-Saber** [comment]
I read online that the problem might be only due to a problem with python 3.7 itself. 
I will try it with python 3.6 to check.

**Comment by Morteza-M-Saber** [comment]
It was the problem with python 3.7.
Switching to python3.6 solves the problem.

**Comment by mgalardini** [comment]
Great to hear the issue was solved. I imagine you were not using the latest release (v 1.2.0) which should have fixed the bug for python 3.7
