### ISSUE TITLE
k-mer association fails with IndexError

### ISSUE THREAD

**Issue by molleraj** [mgalardini/pyseer#66]
When using the newest version of pyseer with python 3.6.7, I get the following issue. I have formatted my phenotype data to match the requirement ("sample \t continuous" header, two tab-delimited columns with sample names and continuous data). 

I executed this command in a for loop:
nohup python ~/pyseer/pyseer-runner.py --phenotypes $METADATAPATH2/$i.pheno --kmers fsm_kmers2.txt.gz --distances mash.tsv --cpu 15 --output-patterns $i"_"kmer2_patterns.txt > $i"_"kmers2.txt &

This is the output after pyseer crashes
(py36) molleraj@loma:~/FASTA$ more pyopyseer_kmers2.txt
variant af      filter-pvalue   lrt-pvalue      beta    beta-std-err    intercept       PC1     PC2     PC3     PC4     PC5     PC6     PC7     PC8     PC9     PC10    notes
/data1/home/molleraj/miniconda2/envs/py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/data1/home/molleraj/miniconda2/envs/py36/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Read 259 phenotypes
Detected continuous phenotype
Structure matrix has dimension (264, 264)
Analysing 255 samples found in both phenotype and structure matrix
Traceback (most recent call last):
  File "/data1/home/molleraj/pyseer/pyseer-runner.py", line 8, in <module>
    main()
  File "/data1/home/molleraj/pyseer/pyseer/__main__.py", line 659, in main
    options.cpu*options.block_size))
  File "/data1/home/molleraj/miniconda2/envs/py36/lib/python3.6/multiprocessing/pool.py", line 296, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/data1/home/molleraj/miniconda2/envs/py36/lib/python3.6/multiprocessing/pool.py", line 398, in _map_async
    iterable = list(iterable)
  File "/data1/home/molleraj/pyseer/pyseer/input.py", line 541, in iter_variants
    sample_order)
  File "/data1/home/molleraj/pyseer/pyseer/input.py", line 342, in read_variant
    '|')[1].lstrip().split())
IndexError: list index out of range

I do not get this issue with SNP or COG association.

**Comment by mgalardini** [comment]
Hi,

Sorry to hear you got this error; would you be able to share a few lines
from your kmer file? Given the error does not happen with vcf or cog inputs
there might be something going on there.

Best,
M

**Comment by molleraj** [comment]
OK, no problem! It is gzipped. Let me expand the file and check.

**Comment by molleraj** [comment]
Here is the result of head fsm_kmers2.txt:
Reading input files...
Read 264 input files and 128660 sequences of total length 1499229628 (includes rev.compl. sequences)
Constructing the data structures...
Construction complete, the main index requires 4654.35 MiB plus 2390.72 MiB for labels.
TTTTTTTTT | 107:19 109:17 115:30 1203158:15 120335:15 120337:14 120338:14 122VISA:15 123:21 126:16 2001013782:7 2002002614:6 2002038081:3 2003718535:11 2006734597:8 2006745535:10 217:12 221:9 312:34 407:15 504:20 506:34 834N:7 BCH-SA-01:5 BCH-SA-02:8 BCH-SA-03:7 BCH-SA-04:5 BCH-SA-05:12 BCH-SA-06:12 BCH-SA-07:6 BCH-SA-08:12 BCH-SA-09:4 BCH-SA-10:8 BCH-SA-11:8 BCH-SA-12:13 BCH-SA-13:8 BCH-SA-14:4 BCH-SA-15:11 CA105:7 CA11:9 CA26:16 CA39:9 CA436:13 CA541:12 CA544:7 CA545:12 CA598:12 CA9:6 CFBREBSa101:17 CFBREBSa102:17 CFBREBSa103:11 CFBREBSa104:18 CFBREBSa105:15 CFBREBSa108:15 CFBREBSa110:15 CFBREBSa112:15 CFBREBSa114:15 CFBREBSa116:15 CFBREBSa117:6 CFBREBSa118:13 CFBREBSa119:15 CFBREBSa121:6 CFBREBSa122:10 CFBREBSa123:18 CFBREBSa125:11 CFBREBSa126:7 CFBREBSa127:7 CFBREBSa129:6 CFBREBSa130:7 CFBREBSa131:1 CFBREBSa133:6 CFBREBSa135:4 CFBREBSa138:6 CFBRSa03:27 CFBRSa04:13 CFBRSa05:9 CFBRSa06:5 CFBRSa07:8 CFBRSa21:14 CFBRSa22:10 CFBRSa23:13 CFBRSa24:20 CFBRSa25:20 CFBRSa26:18 CFBRSa27:19 CFBRSa28:5 CFBRSa29:12 CFBRSa30:6 CFBRSa47:15 CFBRSa48:15 CFBRSa49:11 CFBRSa50:10 CFBRSa51:9 CFBRSa66A:15 CFBRSa66B:15 CFBRSa70:10 CFBRSa74:15 EUH13:8 EUH15:16 EUH25:11 GA12:12 GA15:8 GA231:10 GA27:8 GA48963:10 GA50245:5 GA50819:13 GA51254:7 GA53617:8 GA53649:27 GA984:13 Grady1:7 JE2:5 MN055:13 MN105:8 NRS001:11 NRS002:21 NRS003:12 NRS021:29 NRS022:34 NRS027:11 NRS029:5 NRS035:12 NRS036:10 NRS039:12 NRS049:28 NRS051:24 NRS054:20 NRS063:18 NRS064:6 NRS070:14 NRS071:19 NRS072:9 NRS073:32 NRS074:8 NRS079:20 NRS100:21 NRS102:17 NRS103:3 NRS104:16 NRS105:34 NRS106:71 NRS107:15 NRS108:14 NRS109:3 NRS110:13 NRS111:7 NRS112:7 NRS113:17 NRS114:17 NRS119:22 NRS145:20 NRS148:10 NRS149:19 NRS152:9 NRS157:16 NRS161:11 NRS162:5 NRS164:11 NRS167:17 NRS168:2 NRS169:26 NRS170:5 NRS172:13 NRS175:4 NRS177:19 NRS178:6 NRS180:11 NRS182:22 NRS183:8 NRS185:4 NRS187:4 NRS188:22 NRS189:11 NRS191:4 NRS192:3 NRS194:4 NRS196:17 NRS198:8 NRS199:21 NRS201:13 NRS202:14 NRS203:7 NRS204:6 NRS205:5 NRS207:53 NRS209:11 NRS210:14 NRS211:9 NRS212:12 NRS213:15 NRS214:13 NRS215:4 NRS216:14 NRS217:6 NRS218:11 NRS219:16 NRS220:17 NRS222:13 NRS223:11 NRS224:13 NRS225:4 NRS226:2 NRS227:12 NRS230:7 NRS231:14 NRS232:11 NRS233:18 NRS235:24 NRS237:8 NRS239:3 NRS240:12 NRS241:8 NRS242:7 NRS243:7 NRS245:18 NRS246:5 NRS247:12 NRS248:9 NRS249:14 NRS252:3 NRS253:7 NRS254:12 NRS255:6 NRS256:8 NRS259:2 NRS260:10 NRS262:3 NRS264:8 NRS265:7 NRS266:7 NRS268:24 NRS271:9 NRS272:5 NRS275:8 NRS383:16 NRS386:6 NRS387:8 NY224:12 NY341:17 NY356:11 NY360:12 NY417:17 NY439:17 NY593:9 SR1065:17 SR1129:10 SR1287:6 SR1746:13 SR2091:6 SR220:2 SR2609:14 SR2852:10 SR3569:9 SR3585:8 SR3732:15 SR3777:11 SR4035:10 SR4152:7 SR4153:11 SR4155:12 SR4156:14 SR4187:9
TTTTTTTTTT | 107:9 109:3 115:16 1203158:2 120335:2 120337:2 120338:2 122VISA:3 123:8 126:7 2002002614:2 2003718535:2 2006734597:1 2006745535:1 217:3 221:1 312:22 407:4 504:6 506:18 834N:1 BCH-SA-02:2 BCH-SA-03:1 BCH-SA-04:2 BCH-SA-05:3 BCH-SA-06:4 BCH-SA-07:1 BCH-SA-08:5 BCH-SA-09:1 BCH-SA-10:3 BCH-SA-11:2 BCH-SA-12:5 BCH-SA-13:1 BCH-SA-15:2 CA11:1 CA26:4 CA39:1 CA436:2 CA541:2 CA544:1 CA545:1 CA598:1 CFBREBSa101:6 CFBREBSa102:6 CFBREBSa103:1 CFBREBSa104:6 CFBREBSa105:7 CFBREBSa108:7 CFBREBSa110:7 CFBREBSa112:7 CFBREBSa114:7 CFBREBSa116:4 CFBREBSa118:4 CFBREBSa119:7 CFBREBSa122:4 CFBREBSa123:8 CFBREBSa138:2 CFBRSa03:17 CFBRSa04:5 CFBRSa07:2 CFBRSa21:3 CFBRSa22:1 CFBRSa23:5 CFBRSa24:9 CFBRSa25:9 CFBRSa26:7 CFBRSa27:9 CFBRSa28:1 CFBRSa29:4 CFBRSa30:1 CFBRSa47:7 CFBRSa48:7 CFBRSa49:1 CFBRSa51:1 CFBRSa66A:7 CFBRSa66B:7 CFBRSa74:4 EUH13:1 EUH15:3 EUH25:1 GA12:1 GA15:1 GA231:2 GA27:2 GA48963:1 GA50245:1 GA50819:3 GA51254:1 GA53649:15 GA984:4 Grady1:2 MN055:2 MN105:1 NRS001:1 NRS002:9 NRS003:5 NRS021:14 NRS022:26 NRS027:4 NRS035:4 NRS036:1 NRS039:1 NRS049:16 NRS051:12 NRS054:10 NRS063:13 NRS064:2 NRS070:6 NRS071:10 NRS072:5 NRS073:15 NRS074:2 NRS079:7 NRS100:12 NRS102:9 NRS104:8 NRS105:22 NRS106:57 NRS107:7 NRS108:2 NRS110:2 NRS111:1 NRS112:2 NRS113:11 NRS114:7 NRS119:10 NRS145:9 NRS148:5 NRS149:6 NRS152:3 NRS157:4 NRS161:1 NRS162:1 NRS164:3 NRS167:6 NRS168:1 NRS169:22 NRS172:2 NRS177:13 NRS178:1 NRS180:3 NRS182:16 NRS183:1 NRS185:1 NRS188:9 NRS189:3 NRS192:1 NRS194:1 NRS196:9 NRS198:1 NRS199:11 NRS201:4 NRS202:4 NRS203:1 NRS204:1 NRS205:2 NRS207:34 NRS209:3 NRS210:5 NRS212:5 NRS213:5 NRS214:4 NRS215:1 NRS216:5 NRS217:4 NRS218:3 NRS219:5 NRS220:10 NRS222:6 NRS223:2 NRS224:4 NRS225:2 NRS227:8 NRS230:3 NRS231:5 NRS232:1 NRS233:9 NRS235:12 NRS237:2 NRS239:1 NRS240:1 NRS241:3 NRS242:2 NRS243:3 NRS245:10 NRS246:1 NRS247:7 NRS248:3 NRS249:2 NRS253:2 NRS254:3 NRS255:1 NRS256:1 NRS260:5 NRS264:2 NRS265:1 NRS266:2 NRS268:13 NRS271:1 NRS272:1 NRS275:1 NRS383:9 NRS387:1 NY224:1 NY341:6 NY356:1 NY360:1 NY417:6 NY439:5 NY593:4 SR1065:4 SR1129:1 SR1746:2 SR220:1 SR2609:5 SR2852:4 SR3585:2 SR3732:3 SR3777:1 SR4152:1 SR4153:2 SR4155:3 SR4156:4 SR4187:2
TTTTTTTTTTT | 107:7 115:11 122VISA:1 123:5 126:4 217:1 312:18 407:3 504:3 506:12 BCH-SA-02:1 BCH-SA-06:3 BCH-SA-08:3 BCH-SA-10:1 BCH-SA-12:3 CA26:2 CFBREBSa101:3 CFBREBSa102:3 CFBREBSa104:3 CFBREBSa105:5 CFBREBSa108:5 CFBREBSa110:5 CFBREBSa112:5 CFBREBSa114:5 CFBREBSa116:3 CFBREBSa118:3 CFBREBSa119:5 CFBREBSa122:3 CFBREBSa123:5 CFBREBSa138:1 CFBRSa03:13 CFBRSa04:2 CFBRSa21:1 CFBRSa23:3 CFBRSa24:5 CFBRSa25:6 CFBRSa26:4 CFBRSa27:6 CFBRSa29:3 CFBRSa47:5 CFBRSa48:5 CFBRSa66A:5 CFBRSa66B:5 CFBRSa74:2 GA50819:1 GA53649:11 GA984:2 NRS002:6 NRS003:4 NRS021:10 NRS022:21 NRS027:1 NRS035:2 NRS049:13 NRS051:9 NRS054:6 NRS063:11 NRS064:1 NRS070:5 NRS071:7 NRS072:4 NRS073:9 NRS079:3 NRS100:8 NRS102:6 NRS104:5 NRS105:17 NRS106:51 NRS107:3 NRS110:1 NRS113:8 NRS114:3 NRS119:7 NRS145:6 NRS148:3 NRS149:2 NRS152:1 NRS157:3 NRS164:2 NRS167:2 NRS169:18 NRS177:10 NRS180:2 NRS182:12 NRS188:5 NRS196:5 NRS199:8 NRS201:2 NRS202:2 NRS205:1 NRS207:24 NRS209:1 NRS210:2 NRS212:2 NRS213:1 NRS214:2 NRS216:1 NRS217:2 NRS218:1 NRS219:2 NRS220:8 NRS222:3 NRS224:2 NRS225:1 NRS227:7 NRS231:1 NRS233:6 NRS235:8 NRS241:2 NRS245:5 NRS247:4 NRS254:2 NRS260:4 NRS264:1 NRS268:11 NRS383:7 NY341:4 NY417:3 NY439:3 NY593:3 SR1065:3 SR2609:4 SR2852:3 SR4156:1
TTTTTTTTTTTT | 107:6 115:8 123:4 126:2 312:15 407:2 504:2 506:9 BCH-SA-06:2 BCH-SA-08:2 BCH-SA-12:2 CA26:1 CFBREBSa101:2 CFBREBSa102:2 CFBREBSa104:2 CFBREBSa105:4 CFBREBSa108:4 CFBREBSa110:4 CFBREBSa112:4 CFBREBSa114:4 CFBREBSa116:2 CFBREBSa118:2 CFBREBSa119:4 CFBREBSa122:2 CFBREBSa123:3 CFBRSa03:11 CFBRSa23:2 CFBRSa24:3 CFBRSa25:4 CFBRSa26:3 CFBRSa27:4 CFBRSa29:2 CFBRSa47:4 CFBRSa48:4 CFBRSa66A:4 CFBRSa66B:4 CFBRSa74:1 GA53649:8 GA984:1 NRS002:5 NRS003:3 NRS021:8 NRS022:17 NRS035:1 NRS049:11 NRS051:7 NRS054:3 NRS063:10 NRS070:4 NRS071:6 NRS072:3 NRS073:6 NRS079:2 NRS100:6 NRS102:4 NRS104:3 NRS105:14 NRS106:46 NRS107:1 NRS113:6 NRS114:2 NRS119:6 NRS145:5 NRS148:1 NRS149:1 NRS157:2 NRS164:1 NRS167:1 NRS169:14 NRS177:9 NRS180:1 NRS182:11 NRS188:3 NRS196:3 NRS199:6 NRS201:1 NRS202:1 NRS207:16 NRS210:1 NRS212:1 NRS214:1 NRS217:1 NRS219:1 NRS220:7 NRS222:2 NRS224:1 NRS227:6 NRS233:4 NRS235:7 NRS241:1 NRS245:3 NRS247:2 NRS254:1 NRS260:3 NRS268:9 NRS383:6 NY341:3 NY417:2 NY439:2 NY593:2 SR1065:2 SR2609:3 SR2852:2
TTTTTTTTTTTTT | 107:5 115:7 123:3 312:12 407:1 504:1 506:6 BCH-SA-06:1 BCH-SA-08:1 BCH-SA-12:1 CFBREBSa101:1 CFBREBSa102:1 CFBREBSa104:1 CFBREBSa105:3 CFBREBSa108:3 CFBREBSa110:3 CFBREBSa112:3 CFBREBSa114:3 CFBREBSa116:1 CFBREBSa118:1 CFBREBSa119:3 CFBREBSa122:1 CFBREBSa123:1 CFBRSa03:9 CFBRSa23:1 CFBRSa24:2 CFBRSa25:2 CFBRSa26:2 CFBRSa27:3 CFBRSa29:1 CFBRSa47:3 CFBRSa48:3 CFBRSa66A:3 CFBRSa66B:3 GA53649:5 NRS002:4 NRS003:2 NRS021:6 NRS022:13 NRS049:9 NRS051:5 NRS054:1 NRS063:9 NRS070:3 NRS071:5 NRS072:2 NRS073:3 NRS079:1 NRS100:5 NRS102:3 NRS104:2 NRS105:11 NRS106:42 NRS113:5 NRS114:1 NRS119:5 NRS145:4 NRS157:1 NRS169:10 NRS177:8 NRS182:10 NRS188:1 NRS196:1 NRS199:5 NRS207:10 NRS220:6 NRS222:1 NRS227:5 NRS233:3 NRS235:6 NRS245:2 NRS260:2 NRS268:8 NRS383:5 NY341:2 NY417:1 NY439:1 NY593:1 SR1065:1 SR2609:2 SR2852:1
TTTTTTTTTTTTTT | 107:4 115:6 123:2 312:10 506:4 CFBREBSa105:2 CFBREBSa108:2 CFBREBSa110:2 CFBREBSa112:2 CFBREBSa114:2 CFBREBSa119:2 CFBRSa03:7 CFBRSa24:1 CFBRSa25:1 CFBRSa26:1 CFBRSa27:2 CFBRSa47:2 CFBRSa48:2 CFBRSa66A:2 CFBRSa66B:2 GA53649:3 NRS002:3 NRS003:1 NRS021:5 NRS022:10 NRS049:8 NRS051:3 NRS063:8 NRS070:2 NRS071:4 NRS072:1 NRS073:2 NRS100:4 NRS102:2 NRS104:1 NRS105:9 NRS106:38 NRS113:4 NRS119:4 NRS145:3 NRS169:7 NRS177:7 NRS182:9 NRS199:4 NRS207:8 NRS220:5 NRS227:4 NRS233:2 NRS235:5 NRS245:1 NRS260:1 NRS268:7 NRS383:4 NY341:1 SR2609:1

**Comment by mgalardini** [comment]
Ah I see, you also have the stderr messages in there; removing the first 4
lines should be enough to make it work.

**Comment by molleraj** [comment]
Awesome. I guess I should wait until the kmer file fully expands and remove stderr messages before and after the kmers. Then I will write what the new output is.

**Comment by molleraj** [comment]
Thanks for your help!

**Comment by suzlbach** [comment]
Hi molleraj,

Can you instruct me how to generate the file fsm_kmers.txt.gz?

I generate the file fsm_file_list.txt which basically contains the paths to all of my assemblies. Then I run the script as in the tutorial but the output fsm_kmers is empty so I'm not sure where I went wrong.

Thanks a lot!

**Comment by anhvu989** [comment]
I encounter the same problem and don't know how to fix it. I also try to generate the file with the tutorial data set but the file fsm_kmers.txt.gz is also empty. fsm-lite doesn't raise any errors so I am kinda stuck

**Comment by mgalardini** [comment]
Hi, can you try to use another tool such as [unitig-counter](https://github.com/bacpop/unitig-counter)?

**Comment by anhvu989** [comment]
Hi, Thank you!  I reinstalled fsm-lite through Conda and now it works! previously I cloned it from the git-hub repository.
