### ISSUE TITLE
Pyseer prompts uncontrolled number of processes in computer clusters

### ISSUE THREAD

**Issue by Morteza-M-Saber** [mgalardini/pyseer#68]
I am trying to run pyseer on a series of datasets through a pipeline on a compute cluster (ComputeCanada) and it causes a strange error. Here is the note by cluster admin regarding the job running pyseer:

> I noticed that your job  is asking for 32 cpu cores, but is starting to use many more threads than that. This will cause many context switches, inefficient use of the processors on the node, and poor performance of your code. 

And trying to run the job using  a different setting, apparently the error appeared again 

>  According to the Graham sysadmin your Python jobs are again creating havoc by spinning off a huge number of threads/processes:
> [root@gra572:~] uptime
> 20:35:54 up 70 days, 0 min,  1 user,  load average: 978.96, 972.12, 966.96
> 
> [root@gra572:~] ps -fu masih|wc -l
> 41
> 
> [root@gra572:~] ps -Lfu masih|wc -l
> 1069

I am using latest version of pyseer installed using conda and --cpu option is set to 32, so I was expecting 32 processes at max and and it is the first time I see a python code causes such error. Searching online and asking cluster admins, I could not find the reason why this is happening so I was wondering whether you know the cause of this behavior of pyseer and its solution (Although it might not be a real bug in pyseer).

Thanks

**Comment by mgalardini** [comment]
Hi,

sorry to hear that; we know this could be caused by numpy and to the best of our knowledge we were accounting for it (e.g. see here: https://github.com/mgalardini/pyseer/blob/master/pyseer/__main__.py#L15). Perhaps your cluster has a version of numpy compiled using different libraries?

Best,
Marco
