### ISSUE TITLE
how to find linkage for continue phenotype?

### ISSUE THREAD

**Issue by sekhwal** [mgalardini/pyseer#73]
Hi,
I have got following result of varients, could you help me in the process to find linkage for continue phenotype.
I am trying following command to find linkage for continue phenotype, but not sure how to generate vcf.gz 
pyseer --phenotypes resistances.pheno --vcf snps.vcf.gz --load-m mash_mds.pkl --lineage --print-samples > penicillin_SNPs.txt

**Comment by mgalardini** [comment]
Hi,

the `snps.vcf.gz` file would be the file containing your variants; that would be derived from any SNP calling pipeline of your choice.

Hope this helps,
Marco
