### ISSUE TITLE
ImportError: cannot import name 'factorial' from 'scipy.misc'

### ISSUE THREAD

**Issue by avantonder** [mgalardini/pyseer#74]
Hi,

I installed pyseer today and when I tried to run it (even just pyseer -h), I got the following error:

```
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/bin/pyseer", line 6, in <module>
    from pyseer.__main__ import main
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/__main__.py", line 39, in <module>
    from .model import fixed_effects_regression
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/model.py", line 17, in <module>
    import statsmodels.formula.api as smf
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/statsmodels/formula/api.py", line 15, in <module>
    from statsmodels.discrete.discrete_model import MNLogit
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial' from 'scipy.misc' (/home/ec2-user/miniconda3/lib/python3.7/site-packages/scipy/misc/__init__.py)
```

A quick google brought me here:

https://github.com/statsmodels/statsmodels/issues/5759

It appears to be a recent change (last few days) and I tried using the suggested workaround:

```
pip install --upgrade Cython
pip install --upgrade git+https://github.com/statsmodels/statsmodels
```

This got me past the first error but generated a second:

```
pyseer --phenotypes resistances.pheno --kmers all_31mers.gz --distances mash.tsv --save-m mash_mds --max-dimensions 6 --cpu 4 > pip_taz_kmers.txt
Read 1371 phenotypes
Detected binary phenotype
Structure matrix has dimension (1371, 1371)
Analysing 1371 samples found in both phenotype and structure matrix
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/__main__.py", line 346, in main
    null_fit = fit_null(p.values, m, cov, options.continuous)
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/model.py", line 99, in fit_null
    null_mod = smf.Logit(p, v)
AttributeError: module 'statsmodels.formula.api' has no attribute 'Logit'
```

Any ideas?

Thanks,

Andries

**Comment by avantonder** [comment]
I had a bit of a play to see if I could resolve this issue (I have a bit of a deadline) and I changed the following in `model.py`:

`import statsmodels.formula.api as smf` to `import statsmodels.discrete.discrete_model as smf`

which seemed to do the trick.  However when I try to run the following command I get an error:

```
pyseer --phenotypes resistances.pheno --kmers all_31mers.gz --distances mash.tsv --save-m mash_mds --max-dimensions 6 --cpu 4 > pip_taz_kmers.txt

Read 1371 phenotypes
Detected binary phenotype
Structure matrix has dimension (1371, 1371)
Analysing 1371 samples found in both phenotype and structure matrix
Traceback (most recent call last):
  File "/home/ec2-user/miniconda3/bin/pyseer", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/__main__.py", line 659, in main
    options.cpu*options.block_size))
  File "/home/ec2-user/miniconda3/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/ec2-user/miniconda3/lib/python3.7/multiprocessing/pool.py", line 383, in _map_async
    iterable = list(iterable)
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/input.py", line 537, in iter_variants
    sample_order)
  File "/home/ec2-user/miniconda3/lib/python3.7/site-packages/pyseer/input.py", line 338, in read_variant
    '|')[1].lstrip().split())
IndexError: list index out of range
```
I used `dsk` and `combineKmers` to generate the kmer file:

```
ls -1 *.fasta > list_reads

/home/ec2-user/dsk/build/bin/dsk -file list_reads

/home/ec2-user/dsk/build/bin/dsk2ascii -file list_reads.h5 -out list_reads_dsk.txt

combineKmers -r all_31mers.txt -o all_31mers --min_samples 2
```
and `mash` to generate the distance file:

```
mash sketch -s 10000 -o samples *.fasta

mash dist samples.msh samples.msh | square_mash > mash.tsv
```

Any help would be gratefully accepted.

**Comment by mgalardini** [comment]
Hi,

really sorry you are being bitten by this; I will look into this later
today, but for a hotfix may I suggest you to create a virtual environment
and install pyseer's dependencies with a version that doesn't trigger these
errors?

Best,
Marco

**Comment by mgalardini** [comment]
Also, regarding the last error you are seeing, can you check if your kmer file has the right format?

Try:
`zcat all_31mers.gz | head`

Which should look something like this:
`AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA | sample_616:1 sample_1324:1 sample_1181:1 sample_730:1 sample_1327:1 sample_667:1 sample_1580:1 sample_1800:1 sample_362:1 sample_109:1 sample_661:1 sample_415:1 sample_43:1 sample_1096:1 sample_821:1 sample_983:1`

Marco

**Comment by avantonder** [comment]
The output of zcat all_31mers.gz | head is

GGGGGCTTTCCAGCCGGGACCAACCCCCCCC list_reads_dsk:2
GGGGTTAGTTTAACCAGCAGGTGCATCCCCC list_reads_dsk:10
GGGGTATGTGCCGCTGTATGAAGCATCCCCC list_reads_dsk:16
GGGGCGGCCTTCCCTGCAGATTAGCCCCCCC list_reads_dsk:279
GGGGCACTGCGTCGGGGTTTACGATACCCCC list_reads_dsk:7
GGGGATGGCTCGCTGTGGCGAACCATCCCCC list_reads_dsk:2
GGGTGATGACCAACTTTCAGCAATATCCCCC list_reads_dsk:10
GGGTTCAAGGAATAGCCGTAGCTGTCGCCCC list_reads_dsk:9
GGGTTATCTCTTCTGTTGTGCCATAAACCCC list_reads_dsk:1277
GGGTCGTACACTGTAGCGACCTTCAAAACCC list_reads_dsk:15

**Comment by mgalardini** [comment]
Yeah, that doesn't seem like the expected format, which is:

`VARIANT | SAMPLE_1:COUNT SAMPLE_2:COUNT [...]`

**Comment by avantonder** [comment]
I think I know what the problem is; I provided dsk with a list of files which only created one large h5 output file which I then ran combineKmers on.  I’m rerunning dsk to create individual h5 that I’ll then feed to combineKmers. Hopefully that fixes the problem

**Comment by mgalardini** [comment]
Coming back to the original reason you opened this issue, I can confirm the current release of statsmodels on PyPi conflicts with scipy. Since it seems like this will be soon fixed I would just recommend to create a virtualenv:


```git clone https://github.com/mgalardini/pyseer.git
cd pyseer
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
```

This might brake the enet functionality, but the rest should work fine.

**Comment by avantonder** [comment]
So I had run dsk using the list of assemblies which created a single merged k-mer file which was incorrect. I reran dsk on each assembly and merged them using combineKmers which gave me the following output:

GAATAGTAATATCGGTACGGCTGGAAGCTTC ERR435296:1 ERR439691:1
TGAATCCGCTCGCTCACCTTCAGGATTATTC ERR435296:1 ERR439634:1

Which was still in wrong format has it was missing the ‘|’ between the kmer and sample names/frequencies. A quick test revealed that it’ll work if I use awk to insert the ‘|’ so I’m in the process of doing this.  I know the combineKmers script is from the original seer distribution but it may be worth fixing this.

I managed to get round the scipy issue by using a docker implementation of pyseer.

**Comment by johnlees** [comment]
I think I changed that format at some point: the original seer would work with or without the '|' as `fsm-lite` and `dsk-framework` would give either of these outputs depending on version. pyseer does need the pipe character, but I forgot to update that in `combineKmers` -- sorry!

I will update that in the seer package when I get a chance
