### ISSUE TITLE
how is define continuous phenotype in pyseer

### ISSUE THREAD

**Issue by sekhwal** [mgalardini/pyseer#75]
Hi,
Please let me know, how is define continuous phenotype in pyseer
[phyD-linkage.xlsx](https://github.com/mgalardini/pyseer/files/3208706/phyD-linkage.xlsx)
. I have tried with multiple column in input phenotype file and again with a single column file with --phenotype-column <column name>. However, the out come results are same.

#######################
pyseer --phenotypes phenotypes.pheno --phenotype-column 15.deg pres bugwas-matrix.Rtab --distances mash.tsv --save-m mash_mds --max-dimensions 7> 15.deg.association.txt

**Comment by mgalardini** [comment]
Hi,

sorry, I'm not quite sure what your question exactly is, but if you want to force pyseer to interpret a phenotype column as a continuous phenotype you can do it by adding `--continuous` to your command.

M

**Comment by sekhwal** [comment]
Could you please edit this command for continuous phenotype where should I use --continuous.
##########
pyseer --phenotypes phenotypes.pheno --pres bugwas-matrix.Rtab --distances mash.tsv --save-m mash_mds --max-dimensions 7> 15.deg.association.txt

**Comment by mgalardini** [comment]
Anywhere between `pyseer` and the `>` sign is fine

**Comment by sekhwal** [comment]
As I understood well about continuous phenotype; pyseer takes values whatever in a column of input phenotype file not a binary format. If so, do I need to RUN pyseer for EACH phenotype column in phenotype input file.
Thanks.

**Comment by mgalardini** [comment]
Yes, correct, you would need to run pyseer for each column you want an association with. Use `--continuous` if you want to make sure pyseer treats each column as a continuous phenotype.

I'm gonna close the issue
