### ISSUE TITLE
How to interpret the pyseer's results of significant variants in graphics plot.. 

### ISSUE THREAD

**Issue by sekhwal** [mgalardini/pyseer#78]
Hi,

I need to interpret the output file of significant variants in graphics representation. Should I use iTOL or Cytoscape or la bugWAS to make plots. 
 
I have finally lineage effect variants file, let me know if I can plot it on the tree a la bugWAS or even iTOL or any other way to show that ‘yes’ there are some lineages that effects greater on phenotype.

Thank you,

**Comment by johnlees** [comment]
Examples of visualisation, including interpretation of lineage effects, can be found in the tutorial:
https://pyseer.readthedocs.io/en/master/tutorial.html#

Also see this R code:
https://github.com/johnlees/carriage-duration/blob/master/manhattan_plots.R
