### ISSUE TITLE
Elastic net building

### ISSUE THREAD

**Issue by nwheeler443** [mgalardini/pyseer#80]
Hi, 

I'm trying to use the elastic net function to predict phenotypes using pyseer. After reading in all the variants I get this error message:
...
Saved enet variants as enet_setup.pkl
Applying correlation filtering
100%|██████████| 109291/109291 [02:25<00:00, 748.74variants/s]
Fitting elastic net to top 81968 variants
Traceback (most recent call last):
  File "/nfs/users/nfs_n/nw17/installations/pyseer/pyseer-runner.py", line 8, in <module>
    main()
  File "/nfs/users/nfs_n/nw17/installations/pyseer/pyseer/__main__.py", line 600, in main
    enet_betas = fit_enet(p, all_vars, cov, options.continuous, options.alpha, options.n_folds, options.cpu)
  File "/nfs/users/nfs_n/nw17/installations/pyseer/pyseer/enet.py", line 158, in fit_enet
    nfolds = n_folds, alpha = alpha, parallel = n_cpus)
  File "/lustre/scratch118/infgen/team81/nw17/miniconda3/envs/pyseer/lib/python3.6/site-packages/glmnet_python/cvglmnet.py", line 260, in cvglmnet
    ma = scipy.tile(scipy.arange(nfolds), [1, scipy.floor(nobs/nfolds)])
  File "/lustre/scratch118/infgen/team81/nw17/miniconda3/envs/pyseer/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 1243, in tile
    return c.reshape(shape_out)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

I ran the command:
python3 ~/installations/pyseer/pyseer-runner.py --cpu 16 --enet --vcf genes_and_snps.vcf.gz --phenotypes metadata.txt --phenotype-column GEN --save-model enet_GEN --save-enet enet_setup > GEN.enet

I also haven't managed to load the saved .pkl file to run this again, instead I get:
Terminated
Read 4140 phenotypes
Detected binary phenotype
Reading all variants
Traceback (most recent call last):
  File "/nfs/users/nfs_n/nw17/installations/pyseer/pyseer-runner.py", line 8, in <module>
    main()
  File "/nfs/users/nfs_n/nw17/installations/pyseer/pyseer/__main__.py", line 554, in main
    var_file_original, var_indices, saved_samples, loaded = pickle.load(pickle_obj)
ValueError: not enough values to unpack (expected 4, got 3)

I would appreciate any help with these two issues!

Best,
Nicole

**Comment by mgalardini** [comment]
Hi! I believe I saw this already, how did you install pyseer? Did you use `pip`? It might work if installed with `conda`, but I am not 100% sure.

**Comment by mgalardini** [comment]
Ah sorry, I see from the error message that you did use `conda`. Can you run the following command inside your `conda` environment so that I can see which version of the `glmnet` package you are using?

`pip freeze | grep glmnet`

Also which version of pyseer are you using?

**Comment by nwheeler443** [comment]
I got glmnet-py==0.1.0b2, and I re-installed pyseer a few days ago

**Comment by mgalardini** [comment]
I will look into this soon I hope, there might be some interference with the versions of some libraries pyseer depends on...

**Comment by johnlees** [comment]
Sorry for the slow reply – I have been away

The unpacking error points to a version mismatch somewhere I think, as at some point I added an extra stored value for the hash of the analysed file.
This inconsistency was probably caused by me anyway.

I have some new code for this which fixes some bugs and adds some features that I will try and merge tomorrow. Hopefully that should fix the issue.

**Comment by johnlees** [comment]
Would you be able to try again after pulling the code from the master branch?
If you're still running into the issue could you point me to the location of the files and I'll look into it further

**Comment by nwheeler443** [comment]
It's working now! Thanks for the help :)
