### ISSUE TITLE
Execution not stopped when not providing a distance matrix and no --no-distances

### ISSUE THREAD

**Issue by LeonardosMageiros** [mgalardini/pyseer#82]
Hi, 

I am trying to use pyseer with the files given in the tutorial. 
I have installed pyseer in a clean conda environment and every time I try to run pyseer I get the following: 
![image](https://user-images.githubusercontent.com/28563735/61304357-ef406b00-a7e0-11e9-8697-14d8baa241e6.png)

Can you please help me understand what is wrong with my installation?

Thank you in advance for your time and help.
Best 
Leonardos

**Comment by mgalardini** [comment]
Hi, sorry to hear you bumped into this; I believe this error is caused by the fact that you are not providing a distance matrix but omitting the `--no-distances` option. Should have failed with a more gracious error message, so we'll fix that. thanks for spotting it.

**Comment by LeonardosMageiros** [comment]
Thank you for the quick response. 

I believe that the problem is not that though as I have tried the --no-distances flag. Look Below: 
![image](https://user-images.githubusercontent.com/28563735/61381204-a05b0a00-a8a2-11e9-86e1-9419206e3084.png)

Let me know if I can provide any additional info. 

Best 
Leonardos

**Comment by mgalardini** [comment]
Yeah, that is a separate problem (see #83) that I hope to fix today too. For now you can hot-fix it by doing:

```
conda remove statsmodels
conda install statsmodels=0.8.0 pyseer
```

Hope this helps

**Comment by LeonardosMageiros** [comment]
Ok so now trying to run 
conda install statsmodels=0.8.0 pyseer
gives the following:

![image](https://user-images.githubusercontent.com/28563735/61388058-309f4c00-a8af-11e9-978f-65b213e30dea.png)

Any ideas? 
Thank you very much

**Comment by mgalardini** [comment]
Maybe you can solve this by updating conda itself first?
