### ISSUE TITLE
Pathway burden testing

### ISSUE THREAD

**Issue by fbemm** [mgalardini/pyseer#89]
I am planning to burden test a pathogen pan-genome after some first evidence popped up that multiple genes might be involved in my phenotype with different lines showing LoF's in different genes. I generated a couple of pathway assignments using KEGG and Reactome. The assignment resulted in quiet a number of genes being part of multiple pathways, often because Reactome defines them nested. Question now, is it possible to assign a region to multiple pathways/entries in the burden file?

**Comment by fbemm** [comment]
```
CDS1    FM211187:3910-3951
CDS2    FM211187:4006-4057
CDS3    FM211187:4006-4057
```

**Comment by mgalardini** [comment]
Hi, I don't think we can currently parse multiple regions as a single burden test (see here: https://github.com/mgalardini/pyseer/blob/49d2a410d1e45ac181f0b2ff1570d619211ab61f/pyseer/input.py#L364). In theory we could change the format for the regions file to implement such a behavior; @johnlees what do you think? I'd be happy to do it myself...

**Comment by mgalardini** [comment]
Hi, could you checkout [this branch](https://github.com/mgalardini/pyseer/tree/pathway-burden) and try the proposed change? You can specify multiple regions for a single burden test separating them with a comma:

`CDS3    FM211187:3910-3951,FM211187:4006-4057`

**Comment by johnlees** [comment]
This looks really useful! A proposed documentation change would be to simply change the example given:
```
CDS1    FM211187:3910-3951
CDS2    FM211187:4006-4057
```
to include one multi-region operon:
```
CDS1    FM211187:3910-3951
pathway1    FM211187:4006-4057,FM211187:5673-5777
```
