### ISSUE TITLE
"Dominant" encoding for missing vcf variants for burden testing

### ISSUE THREAD

**Issue by mgalardini** [mgalardini/pyseer#90]
I was working on #89 when I noticed a possible bug when reading a vcf file and doing burden testing.

It seems to me that we should populate the presence/absence dictionary `d` checking if the sample is already set ([see here](https://github.com/mgalardini/pyseer/blob/master/pyseer/input.py#L456)). Otherwise the last variant in the region for burden testing will "dominate" if the variant is missing.

I am not sure if that is the case so it would require some testing. What do you think @johnlees?

**Comment by johnlees** [comment]
Ah yes, I think you are right. 

The code is quite unclear/uncommented for the burden test, but the idea was that `d` is initialised as 0s and then is passed by ref each time, so every variant that is read can flip some of its bits (representing samples) to 1s, and will do nothing if already 1. But missing will mess with this.

I think the best solution would be to make this easier to follow by returning a new `d` for each variant, and then taking a bitwise OR:

| input 1  | input2  | output  |
| ------- | -------- | ----- |
| 0 | 0| 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 1 |
| missing | missing | missing |
|0 | missing | 0 |
|1 | missing | 1 |

which I think could be done with a numpy built-in function, but we could easily write a function if not

**Comment by mgalardini** [comment]
I was thinking we could also implement a "hotfix" in the `read_vcf_var` function itself, checking if a value for a sample is initialized already, so that missingness doesn't overwrite. I'll implement something and we can see how it looks.
