### ISSUE TITLE
awk single line command

### ISSUE THREAD

**Issue by furqan915** [mgalardini/pyseer#94]
Hi,
Looks like a simple question but I havenot found a solution to this. I ran this command but I am getting the errors:
cat <(echo "#CHR SNP BP minLOG10(P) log10(p) r^2") \\
<(paste <(sed '1d' penicillin_SNPs.txt | cut -d "_" -f 2) \\
<(sed '1d' penicillin_SNPs.txt | cut -f 4) | \\
awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' ) | \\
tr ' ' '\t' > penicillin_snps.plot

Errors:
Cat: / dev / FD / 63: no file or directory
Cat: / dev / FD / 62: no file or directory
Paste: / dev / FD / 62: no file or directory

Could you please suggest a solution?
Thanks

**Comment by johnlees** [comment]
Does the file `penicillin_SNPs.txt` definitely exist in the directory?

**Comment by furqan915** [comment]
Yes. This file is in the working directory. I guess the file is really big around 430 Mb that is why perhaps this command is not working. 

I have run the sed commands one by one and they are working fine and saved those results into separate files. But I am not sure how to run awk and cat commands afterward. Could you please suggest me a dissected version of this command?

**Comment by johnlees** [comment]
You could try with temporary files to split up the steps
```
echo "#CHR SNP BP minLOG10(P) log10(p) r^2" > header.txt
sed '1d' penicillin_SNPs.txt | cut -d "_" -f 2 > positions.txt
sed '1d' penicillin_SNPs.txt | cut -f 4 > pvals.txt
paste positions.txt pvals.txt > pyseer_raw_vals.txt
awk '{p = -log($2)/log(10); print "26",".",$1,p,p,"0"}' pyseer_raw_vals.txt > pyseer_vals.txt
cat header.txt pyseer_vals.txt > tmp.plot
tr ' ' '\t' < tmp.plot > penicillin_snps.plot
```

**Comment by furqan915** [comment]
Thanks it worked.
