### ISSUE TITLE
Details of elastic-net model used by pyseer

### ISSUE THREAD

**Issue by Morteza-M-Saber** [mgalardini/pyseer#96]
In a recent paper we used Elastic-net implemented in pyseer and reviewers asked some questions about the details of method that is not fully explained in the documentation.
1) What I can understand from the reference documentation is that pyseer by default keeps the 75% of top markers with coefficients values above zero using elastic net regression and report them as selected marker. Is this correct?
2) After selecting the correlated variants using elastic net, p-values are calculated using the univaraite model. What univariate method is used and is there option to select this univariate model to be either fixed-effect regression as  in SEER or LMM as in FaST-LMM?

Thanks,

**Comment by johnlees** [comment]
A pre-print with details is now available here:
https://www.biorxiv.org/content/10.1101/852426v1

In answer to your specific questions:

1. This is correct, there are a number of supplementary tables showing the effect of this in simulations, and this can be changed with the `--cor-filter` option.
2. By default the p-values given are without population structure adjustment (so either chi-square test or t-test). If you add the `--distances` option you will additionally get p-values from the SEER method. In the pre-print above I used LMM p-values by merging two pyseer runs, but I haven't implemented this in a single step in the code yet
