### ISSUE TITLE
Phenotype file with multiple phenotypes

### ISSUE THREAD

**Issue by Jonathan-Abrahams** [mgalardini/pyseer#97]
Hi,

I am supplying pyseer with a phenotype file which has multiple phenotype columns, each corresponding to resistance to a different antibiotic. (sample in Table 1)

When I do this I get some nice significant genotype-phenotype associations (-log10 values of ~11)

When I split the phenotype file into 4 files, each with only one column , the results are less significant (-log10 values of ~2). (Sample phenotype in table 2). 

Is pyseer testing the association of the genotype with the combined phenotype (could be described as multidrug resistance here), or is it testing a 'collapsed' phenotype-resistance to ANY antibiotic.

I am not sure what I expect pyseer to do! Could you shed some light on the situation?

Table 1. Combined phenotypes

| samples | ethambutol       | isoniazid       | rifampicin |      streptomycin |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ERR551085 |       0      | 0     |  0       | 0 |
| ERR551223 |      0       | 0      | 0       | 0 |
| ERR552204 |      0       | 0      | 0       | 0 |
| ERR551150 |    0       | 0      | 0       | 0 |
| ERR552113  |   1       | 1       | 1       | 1 |
| ERR552505 |   0       | 0      | 0      | 0 |
| ERR552942 |  0       | 0      | 0       | 0 |
| ERR552440 | 0       | 0       |0       | 0 |
| ERR550646 | 0       | 1       | 1       |1 |

Sample 2. Single phenotype

| samples | ethambutol      
| ------------- | ------------- | 
| ERR551085 |       0      | 0     |  
| ERR551223 |      0       | 0      | 
| ERR552204 |      0       | 0      | 
| ERR551150 |    0       | 0      |
| ERR552113  |   1       | 1       | 
| ERR552505 |   0       | 0      | 
| ERR552942 |  0       | 0      |
| ERR552440 | 0       | 0       |
| ERR550646 | 0       | 1       |

**Comment by mgalardini** [comment]
Hi,

by default pyseer will run the association against the last column of your phenotype file; if you run `pyseer -h`, you'll see this message:

```
  --phenotype-column PHENOTYPE_COLUMN
                        Phenotype file column to use [Default: last column]
```

So, if you wanted to obtain the same results as the single phenotype file you indicated here you should add the option ` --phenotype-column ethambutol`

Hope this helps,
Marco

**Comment by Jonathan-Abrahams** [comment]
I did not see that! thank you.
