### ISSUE TITLE
Can pySEER use kmer abundunce as a genotype

### ISSUE THREAD

**Issue by Jonathan-Abrahams** [mgalardini/pyseer#98]
Hi,

I am trying to use pySEER to link gene duplications to a phenotype.

During my brief tests it appeared as though pySEER could not use kmer abudunce as a genotypic signal for this task. For example, if a kmer was present twice in one genome and once in another, that signal was ignored by pyseer. Or indeed if it was present 8 in one genome and 16 in another.

I understand that pySEER would use the absence of a kmer, but how about in this case, with extra copies of the kmer?

At the moment I am specificying duplications using a tab delimited format, but would like to switch over to kmers.

**Comment by mgalardini** [comment]
Hi,

that is correct, at the moment pyseer is looking at presence/absence
patterns, effectively discarding the information you are interested in.

M

**Comment by Jonathan-Abrahams** [comment]
Thanks for your reply. That helps me to stop testing that then!

My plan is to then shoehorn that data into a binary trait format and feed it to pyseer as a tab delimited file.

Do you have any tips for this? I am struggling to think how to elegantly get the data into a binary format. Perhaps kmers which vary in abundance between samples can all be flagged as positive and consistent kmers as negatives.

**Comment by mgalardini** [comment]
I think what you could try is to rewrite the input kmers/unitig file so that anything with one copy or less is encoded as zero, and 1 otherwise.
